### ISSUE TITLE
Setting for main-image div size

### ISSUE THREAD

**Issue by arkhamvm** [lukasz-galka/ngx-gallery#1]
Hello, thanks for awesome plugin!
I need to set up gallery like this:
![gallery](https://cloud.githubusercontent.com/assets/9816112/25114258/b618bb28-2440-11e7-8978-6cdccaf4340b.png)

But how i can main image (red line) width, instead of set gallery (blue line) width?
`imagePercent` setting doest help with width.

**Comment by lukasz-galka** [comment]
At this moment you can achieve this by using transparent border

```
/deep/ ngx-gallery-image {
    border: 20px transparent solid;
} 
```

later I will think about some setting/option.

**Comment by arkhamvm** [comment]
@lukasz-galka, border isn't a good solution, cause backgorund image will cropped. I resized image to needed width/height and change styles like this:
```
/deep/ .ngx-gallery-image {
     background-repeat: no-repeat;
     background-size:   contain;
}
```

**Comment by lukasz-galka** [comment]
@arkhamvm ok, now I understand your problem. I will try to make this as option

**Comment by lukasz-galka** [comment]
@arkhamvm In version 0.8.0 I have added new option "imageSize" and enum:

NgxGalleryImageSize
- Cover (default)
- Contain

**Comment by arkhamvm** [comment]
Great, thx!

**Comment by ronallotalora98** [comment]
buena librería pero no deja modificar el tamaño de la imagen grande
