### ISSUE TITLE
how to make full screen when using inner component.

### ISSUE THREAD

**Issue by m2017atTR** [lukasz-galka/ngx-gallery#10]
Dunno is this question has a weight , but 

how to make full screen when using inner component.
In may app situation is like

```
 AppModule
      Sub Module   router outlet is here that restricting
           MainComponent
           Gallery  Component ngx-gallery is in this component view 
```

**Comment by lukasz-galka** [comment]
Hi, could you give more info or example? Are you talking about fullscreen option or maybe about browser width?

**Comment by lukasz-galka** [comment]
I have added option 'fullWidth', you can see how it works here 
https://lukasz-galka.github.io/ngx-gallery-demo/#fullwidth

let me know if it helps

**Comment by m2017atTR** [comment]
Hi ,
and thanks for replay,

I am using Angular 4 + Angular material 2

So there is Module and component and Material 2 styles.

this.galleryOptions = [
            {
                "previewFullscreen": true,
                "imageArrowsAutoHide": true, "thumbnailsArrowsAutoHide": true,
                "preview": true,
                "thumbnailsColumns": 3, "thumbnailsRows": 2, "thumbnailsPercent": 40, "imagePercent": 60, "thumbnailMargin": 2, "thumbnailsMargin": 2
            },
            { "breakpoint": 500, "width": "300px", "height": "300px", "thumbnailsColumns": 3 },
            { "breakpoint": 300, "width": "100%", "height": "200px", "thumbnailsColumns": 2 }
        ];

![image](https://cloud.githubusercontent.com/assets/25742972/26091703/98542eca-3a15-11e7-99c8-bb5770d5ba4f.png)

**Comment by lukasz-galka** [comment]
Ok, now I understand your problem. I will try to fix it at evening.

**Comment by lukasz-galka** [comment]
Preview has positon fixed (ledt/top 0px), so element is positioned relative to the browser window. 

There are two options for behaviour described by you
1) your content is in iframe and we can't do anything with this - iframe is creating context for fixed position
2) one of gallery parents have 'webkit-transform: translate3d(0,0,0)' and this parent as described here http://stackoverflow.com/a/36857029/5946227 is creating new context for position fixed - here you should remove this style

**Comment by m2017atTR** [comment]
Oh , ok
I ll give a try as soon as possible.

thanks for guidance...

**Comment by lukasz-galka** [comment]
I have checked material code and this behaviour is because of class `mat-sidenav-content` which has `transform` property. There are two tickets about this issue in material repository https://github.com/angular/material2/issues/4873 and https://github.com/angular/material2/issues/998

At this moment there is one option to fix this behaviour
```
.mat-sidenav-container, .mat-sidenav-content {
    transform: none !important;
}
```
