### ISSUE TITLE
Custom thumbnail template

### ISSUE THREAD

**Issue by eugene-sedykh** [lukasz-galka/ngx-gallery#103]
Hi!
Is there any possibility to customize thumbnail template? 
I want to have an icon (times) in a corner of a thumbnail and fire some ImageDeleteEvent clicking on it.
Could you please advise how I can achieve such behavior?
I tried to extend NgxGalleryThumbnailsComponent to change metadata template, but to make it work we need also to modify NgxGalleryComponent template. And it's getting a bit messy and leads to a lot of errors.
Also I tried to change thumbnails template using reflect-metadata. But couldn't get the component's metadata annotation:
`Reflect.getMetadata('annotations', NgxGalleryThumbnailsComponent)` returns undefined.
It returns undefined even for a component written by me. Looks like I use the reflect library incorrectly.

**Comment by lukasz-galka** [comment]
Hi @eugene-sedykh, thanks to @DMcNamara now it is possible. Please check version `4.3.0` and this plunker https://plnkr.co/edit/S0AsmOzS4OoZ9RDRu2Xz?p=preview

**Comment by eugene-sedykh** [comment]
This is awesome! Thanks a lot!
