### ISSUE TITLE
CSS style on active thumbnail

### ISSUE THREAD

**Issue by vh13294** [lukasz-galka/ngx-gallery#104]
Hi,

Is there any way I can add CSS style to the thumbnail when it is active?
Like for example changing the opacity or showing a box-border.
Note*: I can keep track of the current active thumbnail using (change) with $event.

**Comment by lukasz-galka** [comment]
Hi @vh13294, active thumbnail has class `ngx-gallery-active`, example here https://plnkr.co/edit/L4J9kNzYI7fSodG7eD6p?p=preview

**Comment by lukasz-galka** [comment]
I have created also `Styling` section in readme https://github.com/lukasz-galka/ngx-gallery#styling

**Comment by vh13294** [comment]
Thanks you so much!
I really appreciate it.
