### ISSUE TITLE
Any way to inject custom templates?

### ISSUE THREAD

**Issue by karljv** [lukasz-galka/ngx-gallery#105]
Hello

Your module is awesome, but I need to have action buttons on top of the image thumbnail. Is there any way to inject any custom components into the ngx-gallery?

**Comment by karljv** [comment]
![screen shot 2018-01-20 at 12 10 49](https://user-images.githubusercontent.com/3843461/35182323-03158d9c-fddb-11e7-9cd8-aa7b4e696a3a.png)

**Comment by german-e-mas** [comment]
In my opinion, that doesn't depend on the gallery itself. You can always include the gallery inside a container and have buttons above it.

Take a look at this: https://plnkr.co/edit/dcJDRGc4fjPVJYOJp2Fs?p=preview

In the template, there is the following:
```
<div style="position: relative">
  <button style="position: absolute; z-index: 2000;" (click)="actionBtn()">Action</button>
  <ngx-gallery [options]="galleryOptions" [images]="galleryImages"></ngx-gallery>
</div>
```

Just style things up, and you'll have something similar to what you want.

Hope this helps.

**Comment by lukasz-galka** [comment]
@karljv please take a look at https://github.com/lukasz-galka/ngx-gallery/issues/103 there is similar option for image `imageActions` - starting from version `4.3.0`
