### ISSUE TITLE
Issue on V4.2.1

### ISSUE THREAD

**Issue by benoitmugnier** [lukasz-galka/ngx-gallery#107]
ERROR in /node_modules/ngx-gallery/ngx-gallery.d.ts.NgxGalleryComponent.html (8,1254): Property 'previewSelect' is private and only accessible within class 'NgxGalleryComponent'

**Comment by lukasz-galka** [comment]
Hi @benoitmugnier, please checj `4.2.2`

**Comment by benoitmugnier** [comment]
thanks a lot for the fix! 

Have a good day!
