### ISSUE TITLE
thumbnailsSwipe not working on latest iOS version

### ISSUE THREAD

**Issue by vh13294** [lukasz-galka/ngx-gallery#108]
Hi, 

I am experiencing an issue with thumbnail swipe gesture on latest chrome and safari on iOS (iphone 7s and 8plus). 
-I did also try the gesture on your demo page and it's not working either.
-I also include the polyfil and web-animation-js in angular CLI and its still showing the same result

-on iOS:
   +imageSwipe (working)
   +thumbnailsSwipe (not working)
   +thumbnailsArrows (not working) when clicking the slide is not moving

**on android tablets and smartphones, it's working fine.

I'm thinking the problem might come from animation:
-webkit-transition has to be added to support iOS

**Comment by lukasz-galka** [comment]
hi @vh13294, please check version `4.2.3`

**Comment by vh13294** [comment]
thanks you, 
Its working properly now.
