### ISSUE TITLE
Ability to swipe images by keyboard

### ISSUE THREAD

**Issue by mowaiskalam** [lukasz-galka/ngx-gallery#11]
Hi,

I am using this plugin and it's working great. But i am stuck at one position, i need to swipe images next or previous by keyboard arrow buttons when image are open by click, is it possible ? Please let me know, what i have to do if i want to implement this feature.

Thanks

**Comment by lukasz-galka** [comment]
Hi, please check version `0.8.5` and option `previewKeyboardNavigation`
You can see this in action here https://lukasz-galka.github.io/ngx-gallery-demo/#preview-with-image-description

**Comment by mowaiskalam** [comment]
Wow !! you just add it. Thanks
