### ISSUE TITLE
Use thumbnails as links just for images with an url

### ISSUE THREAD

**Issue by chulerias** [lukasz-galka/ngx-gallery#110]
I wonder if it may be possible to use the option "thumbnailsAsLinks" only if an url has been provided for an specific image.
I would like to use some (but not all) of my thumbnails as links, for example to open a pdf file. But at the same time, I would like to continue using the rest of my thumbnails as normal images with the default behaviour.
I tried not passing any url inside the NgxGalleryImage for those that I don't want to use as links, but they send me here:  http://localhost:4200/null

Thanks!

**Comment by lukasz-galka** [comment]
Hi @chulerias, you are right. I will try to add this.

**Comment by sebafra** [comment]
Any updates of this feature?

**Comment by lukasz-galka** [comment]
fixed in `5.7.5`
