### ISSUE TITLE
original size dialog : question

### ISSUE THREAD

**Issue by chris938626** [lukasz-galka/ngx-gallery#112]
Hi Lukasz,
nice gallery 👍 I want to open the image in it's original size and if user's browser size is too small, than scrolling should be possible. Does the ngx-gallery support that? At the moment the image is rendered to the browser resolution. 
Further, I want a preview with an overlaying rectangle as a scroll navigation, to scroll in the original image.
Is that possible? If not, can templates be injected to do that?
Best regards,
Christian

**Comment by lukasz-galka** [comment]
Hi @chris938626 unfortuntely there is no option for that, there is only zoom https://lukasz-galka.github.io/ngx-gallery-demo/#preview-with-zoom

there is also no option for injecting templates. 

Unfortunately lately I don't have time for gallery, so I can't help you.

**Comment by chris938626** [comment]
ok, thank you for the info.
