### ISSUE TITLE
Systemjs

### ISSUE THREAD

**Issue by JuancaValero** [lukasz-galka/ngx-gallery#113]
systemjs does not exist in angular 5, where does the 'map' have to be placed?

**Comment by Dev4mir** [comment]
If you are using Angular-cli you don't need to systemjs so you can escape this step

**Comment by phamtranquocviet** [comment]
I am getting this error:
`./node_modules/ngx-gallery/bundles/ngx-gallery.umd.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/cdsfvpham/Documents/dev/pidx/client/node_modules/ngx-gallery/bundles/ngx-gallery.umd.js'
`
Where should I put, assuming that fixes the error:
`map: {
  'ngx-gallery': 'node_modules/ngx-gallery/bundles/ngx-gallery.umd.js',
}`
