### ISSUE TITLE
Possible to switch image gallery

### ISSUE THREAD

**Issue by dmessier** [lukasz-galka/ngx-gallery#115]
Is it possible to dynamically change the images property to point to a different image array?

**Comment by german-e-mas** [comment]
Of course. You need to change the array.
```
this.galleryImages = newGalleryImages;
```
Check out this Plunker: https://plnkr.co/edit/hszCyPPwRkh4P7yoJtxv?p=preview
Click the button below the gallery: It replaces the images array.

**Comment by dmessier** [comment]
Thanks!  Working great…

 

*	Dave
