### ISSUE TITLE
Issue wile Loading 

### ISSUE THREAD

**Issue by santhoshrajuvysyaraju** [lukasz-galka/ngx-gallery#117]
Hi i Have Integrated The Slider to My Application.  I Have Integrated this to 3 Places In a same file. but it is displaying only at end of page. but it is not displaying at the start of page. only 2 sliders are displaying the third slider was not displaying.

Here Is The  Screenshot of slider.

https://www.awesomescreenshot.com/image/3159760/64c35cfc92920cb37dbd22daad584dc3

Here is The Screenshot of error.

http://prntscr.com/ibuba0

Here is The Code:

<div class="outer">
  <div class="imgdata">
      <div class="limage in">
      
      <ngx-gallery [options]="galleryOptions" [images]="galleryImages"></ngx-gallery>
      </div>
      <div class="data in">
          <div class="productname">{{pdata.name}}</div><br>
          <div  class="reviewlink"><a href="" style="text-decoration:none;">Be The First One To Review This Product</a></div>
          <div class="pricedetails_availability">
              <div class="price ln "><strong>{{pdata.price | number:'2.2' | currency:''}}</strong></div>
              <div class="availability ln">
                  <ul class="tright" type="none">
                      <li><span class="stock clr">In Stock</span></li>
                      <li><span class="sku clr">SKU# &nbsp;{{+pdata.sku}}</span></li>
                  </ul>
              </div>
          </div>
          <div class="qty">
              <form>
                  <div class="qtytext clr">Qty</div><br>
                  <input type="number" name="quantity" class="quan clr" minvalue="1" [(ngModel)]="quantity"><br>
                  <input type="submit" name="addtocart" value="Add To Cart" class="cbtn" (click)="cs.addmorequantity(pdata.sku,quantity)">
               </form>
  
          </div>
          <div class="oplist">
              <ul type="none">
                  <li class="wlist"><i class="fa fa-heart"></i>&nbsp;ADD TO WISH LIST</li>
                  <li class="wlist"> <i class="fa fa-bar-chart-o"></i>&nbsp;ADD TO COMPARE </li>
                  <li class="wlist"><i class="fa fa-envelope"></i>&nbsp;EMAIL</li>
              </ul>
          </div>
      </div>
  </div> 
   

<ngx-gallery [options]="galleryOptions" [images]="galleryImages"></ngx-gallery>
   <ngx-gallery [options]="galleryOptions" [images]="galleryImages"></ngx-gallery>
 

Please Help me to solve The Issue.

**Comment by lukasz-galka** [comment]
Hi @santhoshrajuvysyaraju I have created plunker wit halso 3 galleries and it works https://plnkr.co/edit/Y2yVQak2QD1BWdSqsXmJ?p=preview

Could you try to reproduce this issue using plunker?
https://plnkr.co/edit/D1tdBCeFo6L9tMOCOb9p?p=preview

For me it look like you didn't set `options`, as you can see here https://github.com/lukasz-galka/ngx-gallery/blob/master/src/ngx-gallery.component.ts#L68

**Comment by santhoshrajuvysyaraju** [comment]
@lukasz-galka  Thanks It is Working now. Previously i used to Write The Code Inside The http.get method it is not initiating at the start of document loading. so it is not passing the images and options. after the loading options was passed to last two tags. The First tag doesn't contains options. Now The Issue is solved .

I Have Sent Options First And Then i used to send images. Now It is working.

Thanks For Support
