### ISSUE TITLE
Thumbnails are not displaying

### ISSUE THREAD

**Issue by santhoshrajuvysyaraju** [lukasz-galka/ngx-gallery#118]
Hi i have Integrated your slider it is displaying images but it is not displaying thumbnails. thumbnails property are set to background images it is showing in the console but it is not displaying at display

**Comment by lukasz-galka** [comment]
Hi @santhoshrajuvysyaraju please reproduce it on https://plnkr.co/edit/D1tdBCeFo6L9tMOCOb9p?p=preview

I need an example to work on it.

**Comment by santhoshrajuvysyaraju** [comment]
@lukasz-galka  Thanks i forget to add the no of columns to the thumbnail now it is working. Thanks For The Support.
