### ISSUE TITLE
any option for delete image ?

### ISSUE THREAD

**Issue by ArfanMirza** [lukasz-galka/ngx-gallery#121]
Is there any option for delete image ? 
Need an cross/delete icon over image, on click image should be delete.

**Comment by lukasz-galka** [comment]
https://github.com/lukasz-galka/ngx-gallery/issues/103

**Comment by ArfanMirza** [comment]
Thanks, is there any way, i want show all images. Hide the left/right arrow.

**Comment by lukasz-galka** [comment]
@ArfanMirza you can set thumbnailsRows to your images count. Just for the record, don't ask questions in closed issues.
