### ISSUE TITLE
How to trigger / capture methods ?

### ISSUE THREAD

**Issue by inshaf** [lukasz-galka/ngx-gallery#122]
hi.. I wanted to get the index of the previewing image. I think following will do this 

"show(index: number): void - shows image at index" 

But i dont know how to trigger / capture it. Event on your demo page ( demo for "show prev" and "show next" ) it shows only the code config, not how to trigger those methods. 

Please give us the sample code for trigger / capture "methods" ( show(), showNext(), showPrev() etc )

Thanks for the excellent plugin 👍

**Comment by german-e-mas** [comment]
I believe this issue can guide you: https://github.com/lukasz-galka/ngx-gallery/issues/50

**Comment by inshaf** [comment]
thanks it works... i think better add these sample in the demo pages
