### ISSUE TITLE
Issue with custom action method

### ISSUE THREAD

**Issue by inshaf** [lukasz-galka/ngx-gallery#125]
Hi, i have added "actions" (NgxGalleryAction) to the gallery and it works perfectly ( it shows icons on the top right corner and trigger my custom method ). But when I use "this" keyword within this custom method, it return "NgxGalleryAction" object. This means, i cannot use any variables / objects which are define outside of this method. 

What is the solution for this ?

**Comment by lukasz-galka** [comment]
pls check this plunker https://plnkr.co/edit/S0AsmOzS4OoZ9RDRu2Xz?p=preview

**Comment by inshaf** [comment]
yes... it worked 👍

**Comment by sebafra** [comment]
Hi @lukasz-galka,
The example you provide work perfect for thumbnailActions, but when i use `actions` i get an `undefined` index. I need to get the `link` parameter of the image in order to go to an external url.
Can you help me
Thanks in advance

**Comment by lukasz-galka** [comment]
fixed in `5.5.1`

**Comment by rupesh45** [comment]
How can I trigger a function when I clicked on the thumbnail??
