### ISSUE TITLE
Question: Can I get the plunker for following

### ISSUE THREAD

**Issue by inshaf** [lukasz-galka/ngx-gallery#126]
hi, can i get plunker for https://lukasz-galka.github.io/ngx-gallery-demo/#dynamic-images-change and https://lukasz-galka.github.io/ngx-gallery-demo/#async-images

thanks

**Comment by lukasz-galka** [comment]
@inshaf check demo sources https://github.com/lukasz-galka/ngx-gallery-demo and closed issues.
