### ISSUE TITLE
Question : How to change the image description ?

### ISSUE THREAD

**Issue by inshaf** [lukasz-galka/ngx-gallery#127]
Hi... im allowing user to update the image description when user in the preview mode.  

I have added image action ( a button is showing on the top right corner when previewing ). When user click the action button, it shows a modal window where user enter description. I'm updating this description as follows

this.galleryImages[0]['description'] = "setting new description";

and when i check "this.galleryImages" at console it shows correctly with new updated values but it is not reflecting at image preview. 

What should i do to fix this ?

Thanks in advance

**Comment by lukasz-galka** [comment]
This is because of angular change detection, more here https://github.com/lukasz-galka/ngx-gallery/issues/6

you have to create new reference
```
this.galleryImages[0]['description'] = "setting new description";
this.galleryImages = this.galleryImages.slice(0, this.galleryImages.length)
```
