### ISSUE TITLE
how to get the index of images in gallery?

### ISSUE THREAD

**Issue by faribajpr** [lukasz-galka/ngx-gallery#128]
@lukasz-galka i have a ngx-gallery and a button and i want to print the images that is previewing in the array of images when i click the button. how can i get the index of previewing images?

**Comment by lukasz-galka** [comment]
there is an event `previewChanged` https://github.com/lukasz-galka/ngx-gallery#events

**Comment by lukasz-galka** [comment]
like other events, example here https://github.com/lukasz-galka/ngx-gallery/issues/50#issuecomment-335866838

**Comment by omarmakeen** [comment]
@lukasz-galka 
I can detect if preview changes but how can get index of current image?
