### ISSUE TITLE
Image/thumbnail swipe seems to not be triggering

### ISSUE THREAD

**Issue by erieflin** [lukasz-galka/ngx-gallery#129]
perceived bug: Neither image swipe or thumbnail swipe is working in the gallery on mobile (nexus 6p)
expected behavior: swipe on screen advances the gallery in the direction of swipe
actual behavior: no response occurs
Additional Information:

package.json dependancies
 "dependencies": {
    "@ angular/animations": "^5.1.2",
    "@ angular/common": "^5.1.2",
    "@ angular/compiler": "^5.1.2",
    "@ angular/core": "^5.1.2",
    "@ angular/flex-layout": "^2.0.0-beta.12",
    "@ angular/forms": "^5.1.2",
    "@ angular/http": "^5.1.2",
    "@ angular/platform-browser": "^5.1.2",
    "@ angular/platform-browser-dynamic": "^5.1.2",
    "@ angular/platform-server": "^5.1.2",
    "@ angular/router": "^5.1.2",
    "angular-google-maps": "^2.4.1",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "ng2-file-upload": "^1.2.1",
    "ngx-gallery": "^4.3.0",
    "ngx-modal": "0.0.29",
    "normalize.css": "^7.0.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.14"
  },

app.module imports:
import { BrowserModule } from '@angular/platform-browser';
import { FileUploadModule } from "ng2-file-upload";
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { RoutingModule } from './routing/app.routing';
import { NgxGalleryModule } from 'ngx-gallery';
import 'hammerjs';

gallery settings
[
      {
        thumbnailsColumns: 4,
        thumbnailsArrows: true,
        imageArrows: true,
        preview: false,
        imageAutoPlay: true,
        imageAutoPlayPauseOnHover: true,
        previewAutoPlay: true,
        previewAutoPlayPauseOnHover: true,
        imageSwipe: true,
        thumbnailsSwipe: true
      }
    ];

I also have attempted importing hammerjs into the component

If this is simply something I am missing please advise.
Thanks for making this gallery, it has been quite helpful for us.

**Comment by lukasz-galka** [comment]
Hi @erieflin, could you try on other device? Your configuration looks good. 
I checked on my huawei and it works fine.
