### ISSUE TITLE
Package.json after fork:Question

### ISSUE THREAD

**Issue by chris938626** [lukasz-galka/ngx-gallery#130]
Hi Lukasz,
I forked your gallery. I want to add the forked url to my projects' package.json. 
but I can't add that forked repository. It is not build. After building,  I must copy the content of the dist folder  to the ngx-gallery root direcoty. Is there another process?

The correct entry for the package.json is the dist folder inside  "github:chris938626/ngx-gallery#dist".   So I wrote the postscript "postinstall": "mv dist/* ./", but is there another way ?

In the main project I now can specify   "ngx-gallery": "github:chris938626/ngx-gallery#dist",
How can I specify to use that, without postinstall?
 Best regards,
Christian

**Comment by lukasz-galka** [comment]
Hi @chris938626 I din't try to use this in that way, so I can't help. For local development I use npm link https://github.com/lukasz-galka/ngx-gallery/issues/90

**Comment by chris938626** [comment]
thank you..
