### ISSUE TITLE
How can I call openPreview ?

### ISSUE THREAD

**Issue by isaelblaismod** [lukasz-galka/ngx-gallery#134]
I was wondering how to call or where to call openPreview action from the component ?

Thanks in advance

**Comment by german-e-mas** [comment]
I suggest to look for closed issues. There are many tips and tricks in them.

Perhaps you can find this one useful: https://github.com/lukasz-galka/ngx-gallery/issues/50

**Comment by isaelblaismod** [comment]
The problem is that I want to call if from my component.ts, which gallery isnt defined ...

**Comment by isaelblaismod** [comment]
I can pass my gallery object like so : <div (click)="handleClick(gallery)" ... 

The next probleme is how to call the open preview inside this object ?
