### ISSUE TITLE
Reinit gallery

### ISSUE THREAD

**Issue by dvlasenko96** [lukasz-galka/ngx-gallery#135]
Is there a way to reinit gallery or change gallery options? I need to change thumbnailsRows and thumbnailsColumns depends of the new images that have been passed to the component.

**Comment by german-e-mas** [comment]
Yes, you need to make sure to change the reference of the galleryOptions array. For example:

```
galleryOptions: NgxGalleryOptions[];
this.galleryOptions = [
  {
    thumbnailsColumns: 4,
    thumbnailsRows: 1,
  }
];
```
And somewhere else...
```
const newOptions = [
  {
    thumbnailsColumns: 1,
    thumbnailsRows: 6,
  }
];
this.galleryOptions = newOptions;
```
