### ISSUE TITLE
nglint fix

### ISSUE THREAD

**Issue by Volof** [lukasz-galka/ngx-gallery#14]
Hola man!
Please fix lint, cant push to develop, tnx
$ ng lint
Your global Angular CLI version (1.0.3) is greater than your local
version (1.0.0-rc.2). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

/node_modules/ngx-gallery/lib/ngx-gallery-preview.component.ts[14, 18]: Type boolean trivially inferred from a boolean literal, remove type annotation
/node_modules/ngx-gallery/lib/ngx-gallery-preview.component.ts[26, 20]: Type number trivially inferred from a number literal, remove type annotation
/node_modules/ngx-gallery/lib/ngx-gallery-preview.component.ts[28, 21]: Type boolean trivially inferred from a boolean literal, remove type annotation
/node_modules/ngx-gallery/lib/ngx-gallery-preview.component.ts[6, 15]: The selector of the component "NgxGalleryPreviewComponent" should have prefix "app" (https://goo.gl/cix8BY)
/node_modules/ngx-gallery/lib/ngx-gallery-animation.model.ts[2, 18]: Type string trivially inferred from a string literal, remove type annotation
/node_modules/ngx-gallery/lib/ngx-gallery-animation.model.ts[3, 19]: Type string trivially inferred from a string literal, remove type annotation
/node_modules/ngx-gallery/lib/ngx-gallery-animation.model.ts[4, 20]: Type string trivially inferred from a string literal, remove type annotation
/node_modules/ngx-gallery/lib/ngx-gallery-animation.model.ts[5, 18]: Type string trivially inferred from a string literal, remove type annotation
/node_modules/ngx-gallery/lib/ngx-gallery-image-size.model.ts[2, 19]: Type string trivially inferred from a string literal, remove type annotation
/node_modules/ngx-gallery/lib/ngx-gallery-image-size.model.ts[3, 21]: Type string trivially inferred from a string literal, remove type annotation
/node_modules/ngx-gallery/lib/ngx-gallery.component.ts[26, 22]: Type number trivially inferred from a number literal, remove type annotation
/node_modules/ngx-gallery/lib/ngx-gallery.component.ts[28, 20]: Type number trivially inferred from a number literal, remove type annotation
/node_modules/ngx-gallery/lib/ngx-gallery.component.ts[11, 15]: The selector of the component "NgxGalleryComponent" should have prefix "app" (https://goo.gl/cix8BY)
/node_modules/ngx-gallery/lib/ngx-gallery-arrows.component.ts[4, 15]: The selector of the component "NgxGalleryArrowsComponent" should have prefix "app" (https://goo.gl/cix8BY)
node_modules/ngx-gallery/lib/ngx-gallery-image.component.ts[6, 15]: The selector of the component "NgxGalleryImageComponent" should have prefix "app" (https://goo.gl/cix8BY)
/node_modules/ngx-gallery/lib/ngx-gallery-thumbnails.component.ts[7, 15]: The selector of the component "NgxGalleryThumbnailsComponent" should have prefix "app" (https://goo.gl/cix8BY)

**Comment by lukasz-galka** [comment]
Hi, you should not linting external library. My lib and probably other libraries are emitting *.ts files but they shouldn't. I will try to fix this soon, but at this moment you can exclude node_modules directory from linting as described [here](https://github.com/angular/angular-cli/issues/4350#issuecomment-308140804)

Please update angular-cli.json file
```
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
```

**Comment by Volof** [comment]
Thanks for the quick reply. It works well!
