### ISSUE TITLE
Experiencing gesture issue on mobile

### ISSUE THREAD

**Issue by grantyi** [lukasz-galka/ngx-gallery#141]
It seems that ALL directions of the gesture is being used by the gallery component. I am able to swipe left and right to change the image but swipe up and down to scroll is prevented. 

Here is my gallery options: 

```  imageArrows: false,
        imageSwipe: true,
        preview:false,
        thumbnailsSwipe: true,
        previewSwipe: true,
        thumbnails: false,
        width: "100%",
        height: "250px"

**Comment by kamal0808** [comment]
@lukasz-galka What is the solution to this? I am experiencing the same in v3.1.4

**Comment by PepeBel4** [comment]
Experiencing same issue. Would be very nice to have vertical swiping functionality.

**Comment by lukasz-galka** [comment]
Hi all, I've tested swipe demo https://lukasz-galka.github.io/ngx-gallery-demo/#swipe on my phone (huawei p10) and tablet (samsung galaxy tab s2) - everything works fine. 

I've testes also on the same devices @kamal0808 example and there are some problems with vertical swipe, so I think there is a problem with hammerjs or maybe there is a issue in your code. 

Could someone who has the problem with swipe, test it on the demo page and tell how it works? 

pls give also output of `npm list ngx-gallery hammerjs`. I have ngx-gallery `5.3.2` and hammerjs `2.0.8`

**Comment by PepeBel4** [comment]
I tested the demo and vertical swipe works correctly in the demo.
But on 'my' page; the vertical swipe does not work.

hammerjs@2.0.8 
├── ngx-gallery@5.3.2 

I copied and pasted the example code almost identical into our project.

**Comment by lukasz-galka** [comment]
@PepeBel4 here https://github.com/lukasz-galka/ngx-gallery/blob/master/src/index.ts I disabled vertical scroll in hammerjs, there is a chance that someone or other plugin overrides this configuration. Could you try to add this to your module?

```
import { HammerGestureConfig, HAMMER_GESTURE_CONFIG } from '@angular/platform-browser';

export class CustomHammerConfig extends HammerGestureConfig  {
    overrides = <any>{
        'pinch': { enable: false },
        'rotate': { enable: false }
    };
}

    providers: [
        { provide: HAMMER_GESTURE_CONFIG, useClass: CustomHammerConfig }
    ]
```

**Comment by rmschots** [comment]
@lukasz-galka 
I had the same issue and your custom hammerjs configuration indeed fixes it.
No idea which other library overrides the pinch/rotate settings though.

**Comment by lukasz-galka** [comment]
@rmschots thanks
