### ISSUE TITLE
Image Caption

### ISSUE THREAD

**Issue by djaddo** [lukasz-galka/ngx-gallery#143]
Hello, 

The gallery is amazing!
But, is it possible to add captions to gallery images here: http://prntscr.com/iq65gh

For example:
 ```
this.galleryImages = [
     {
      small: "Url",
      medium: "Url",
      big: "Url",
      caption: "Some caption"
     }
];
```

Thanks!

**Comment by lukasz-galka** [comment]
Hi @djaddo, unfortunately no, but this is simple feature, so I will try to add this soon

**Comment by lukasz-galka** [comment]
@djaddo pls check version `5.2.0` and option `imageDescription` demo here https://lukasz-galka.github.io/ngx-gallery-demo/#image-with-description

**Comment by djaddo** [comment]
Hi @lukasz-galka ,

I can just say wow! 
This was blazing fast!
It works like a charm. 
Thank you for your time and effort.

**Comment by malaa5260** [comment]
add caption as a text where pleaze ?
