### ISSUE TITLE
Custom Actions

### ISSUE THREAD

**Issue by Jonnybravo** [lukasz-galka/ngx-gallery#144]
Hi,

I'm trying to implement a custom action using the option 'imageActions', but I can't find an example. Can you give me a sample?

With this option, is it possible to put a close button directly on the image? I wanted to remove a certain image from the slider with a close icon on the top right corner...

Thanks

**Comment by lukasz-galka** [comment]
Hi @Jonnybravo here you have example with `thumbnailActions` https://github.com/lukasz-galka/ngx-gallery/issues/103

`imageActions` should work in the same, if you still have some issues let me know and give example code

**Comment by Jonnybravo** [comment]
Thanks, I managed to put it to work using 'imageActions' and using the code that you provided.
