### ISSUE TITLE
How to hide arrow icon when there is one image 

### ISSUE THREAD

**Issue by dawlat-netlinks** [lukasz-galka/ngx-gallery#145]
In below gallery, I want that the right and left arrow not showing me until the image becomes more than one how to hide these icons.
![screenshot 5](https://user-images.githubusercontent.com/17270141/37323996-97fc3f22-26a4-11e8-8cd3-e688c9d3d64f.png)

**Comment by lukasz-galka** [comment]
Hi @dawlat-netlinks  you can override disabled arrow style

```
ngx-gallery /deep/ .ngx-gallery-arrow.ngx-gallery-disabled { 
    display: none; 
}
```

example here https://plnkr.co/edit/n4XgbsAdrDdppMLZlnpX?p=preview

**Comment by lukasz-galka** [comment]
I will also try to hide them in code in that situation - today or tomorrow

**Comment by dawlat-netlinks** [comment]
@lukasz-galka Thanks a lot for the reply and that works form.
