### ISSUE TITLE
Preview not working correctly in component with changeDetection OnPush

### ISSUE THREAD

**Issue by Jonnyprof** [lukasz-galka/ngx-gallery#147]
When the ngx-gallery is placed in a component with changeDetection set OnPush, and you click on a image to see the preview it not detect the change until you move the mouse.
You have the same behaviour when you click on the arrow keys.
You can try it at: https://angular-ngx-gallery-push.stackblitz.io/ (https://stackblitz.com/edit/angular-ngx-gallery-push)

I guess this can be fixed with a ChangeDetectorRef and markForCheck in setTimeouts that changes something in the view.
I'll try to fix it and do a PR in my free time.

**Comment by ike18t** [comment]
I ran into this issue as well.  I have opened a PR with the fix: #210

**Comment by tommei** [comment]
Hi, we also have problem with OnPush change detection. Any chance to merge this PR?

**Comment by lukasz-galka** [comment]
pls check `5.8.2`

**Comment by tommei** [comment]
works perfect, thanks!
