### ISSUE TITLE
Is that possible to rotate a image when is on the preview?

### ISSUE THREAD

**Issue by diegoserrat** [lukasz-galka/ngx-gallery#148]
Good afternoon!

I'm looking for some way to rotate a image, when it's on the preview. 
Same way as the lib uses a zoom, is that possible?

**Comment by lukasz-galka** [comment]
Hi @diegoserrat no, it isn't. but I think this is a good idea for a improvement, I will try to add this soon

**Comment by diegoserrat** [comment]
Thank you!

**Comment by lukasz-galka** [comment]
@diegoserrat pls check version `5.3.0` with option `previewRotate` 
demo here https://lukasz-galka.github.io/ngx-gallery-demo/#preview-with-zoom-and-rotate

**Comment by diegoserrat** [comment]
@lukasz-galka I tested and it's working! Awesome!
