### ISSUE TITLE
Possible to add auto sliding?

### ISSUE THREAD

**Issue by RuanKruger** [lukasz-galka/ngx-gallery#15]
Hi 

Is it possible to add an option to auto sliding of the images?

Thanks.

**Comment by lukasz-galka** [comment]
Hi, currenlty I have some problems with aot and version 1.0.0, but after this I can add this feature.

**Comment by RuanKruger** [comment]
Cool, if there is a certain route I can follow please inform me. Thanks for the wonderful gallery :+1:

**Comment by experionathira** [comment]
Any update on this ?

**Comment by lukasz-galka** [comment]
Hi @experionathira  this is my next thing to do, so there is a chance that I will do this today or tomorrow

**Comment by lukasz-galka** [comment]
@experionathira please check version `1.4.0` and this demo https://lukasz-galka.github.io/ngx-gallery-demo/#auto-play
