### ISSUE TITLE
Open in preview on page load

### ISSUE THREAD

**Issue by mediocre-code** [lukasz-galka/ngx-gallery#150]
First off thanks for making this, I really appreciate the amount of options we have.  That being said I'm here to ask for more!  Or additional information on how to achieve my goal, is it possible to open the gallery into preview mode on page load?  Or better yet, open it via typescript when I load the pages into the galleryImages object?

Thanks

**Comment by lukasz-galka** [comment]
Hi @mediocre-code you can open preview via api https://github.com/lukasz-galka/ngx-gallery#methods

example here https://github.com/lukasz-galka/ngx-gallery/issues/20 or https://github.com/lukasz-galka/ngx-gallery/issues/50

**Comment by mediocre-code** [comment]
Ah ViewChild, beautiful! Thanks!
