### ISSUE TITLE
"Preview with fullscreen on start" demo setting thumbnails to it's start

### ISSUE THREAD

**Issue by ANU5253** [lukasz-galka/ngx-gallery#152]
In my project, I have setup the fullscreen on preview open. But it will change the thumbnail to start and arrow is not changing accordingly.

The same problem occurred in the demo with "Preview with fullscreen on start".

Please provide some solution to stop this behaviour.

Thanks in advance.

**Comment by lukasz-galka** [comment]
Hi @ANU5253 I don't understand your problem, please try to explain it one more time - I would like to help.

I assume that we talk about this demo https://lukasz-galka.github.io/ngx-gallery-demo/#preview-with-fullscreen-on-start, for it works fine.

**Comment by ANU5253** [comment]
Hello @lukasz-galka, yes I am talking about the same demo.

Please follow the below steps in that demo.
1) press right arrow at thumbnails and view the last image and click on it
2) now open the preview on clicking above image (which is last image)

Now, you can verify the thumbnails after closing the preview. It is setted to the first, but the arrow is disabled of right side.

**Comment by lukasz-galka** [comment]
@ANU5253 pls check version `5.3.1`, on demo there is still `5.3.0` so you have to install it to see change

**Comment by ANU5253** [comment]
Hello @lukasz-galka,

Thanks for the quick changes in the repository. The new version 5.3.1 solved the thumbnail resizing issue. So, I am closing this issue.

Thanks,
AB
