### ISSUE TITLE
NgxGalleryPreviewComponent generates image with src="#" causing action called twice in Chrome

### ISSUE THREAD

**Issue by Aman-Jojra** [lukasz-galka/ngx-gallery#154]
I have noticed that in line 19 of ng:///NgxGalleryModule/NgxGalleryPreviewComponent.html - 
`<img #previewImage class="ngx-gallery-preview-img ngx-gallery-center" [src]="src ? src : '#'" (click)="$event.stopPropagation()" (mouseenter)="imageMouseEnter()" (mouseleave)="imageMouseLeave()" (mousedown)="mouseDownHandler($event)" (touchstart)="mouseDownHandler($event)" [class.ngx-gallery-active]="!loading" [class.animation]="animation" [class.ngx-gallery-grab]="canDragOnZoom()" [style.transform]="getTransform()" [style.left]="positionLeft + 'px'" [style.top]="positionTop + 'px'"/>
           `
"src" attribute being set when I click on image to load preview. Unless I see preview, image's src attribute remains as "#". I tried with disabling lazy loading as well.

problem with image's src as "#" is that it calls MVC controller again as mentioned in [here](https://bugs.chromium.org/p/chromium/issues/detail?id=64810)

**Comment by lukasz-galka** [comment]
@Aman-Jojra thanks for this bug report. Unfortunately I don't have time lately, PR are welcome.

**Comment by Aman-Jojra** [comment]
Ah thanks for quick turn around. It's working perfect now.
