### ISSUE TITLE
Image AutoPlays when thumbail arrow is clicked few times.

### ISSUE THREAD

**Issue by bibash-mi** [lukasz-galka/ngx-gallery#155]
When thumbnail arrow is continuously clicked a few times, the images will start to autoplay even though AutoPlay is set False. 

Here is my setup for the ngx-gallery: 

    this.galleryOptions = [
           {
             width: '50%',
             height: '900px',
             preview: false,
             previewAutoPlay:false,
             imageSize: NgxGalleryImageSize.Contain,
             imageAutoPlay: false,
             imageArrowsAutoHide: true,
             thumbnailsArrowsAutoHide: true,
             thumbnailsPercent: 20,
             thumbnailSize:"contain",
             thumbnailsMargin: 5,
             thumbnailMargin: 5,
             thumbnailsColumns:6
           },
           {
             breakpoint:1024,
             width: '90%',
             height: '700px',
             preview: false,
             previewAutoPlay:false,
             imageSize: NgxGalleryImageSize.Contain,
             imageAutoPlay: false,
             imageArrowsAutoHide: true,
             thumbnailsArrowsAutoHide: true,
             thumbnailsPercent: 20,
             thumbnailsColumns:6,
             thumbnailSize:"contain",
             thumbnailsMargin: 5,
             thumbnailMargin: 5,
           },
       ];

**Comment by lukasz-galka** [comment]
Hi @bibash-mi I can't reproduce this issue, could you record a video with this issue? Could you reproduce it using plunker https://plnkr.co/edit/D1tdBCeFo6L9tMOCOb9p?p=preview ?
