### ISSUE TITLE
page strucks while loading images page hangs in chrome only..

### ISSUE THREAD

**Issue by vignesh007vicky** [lukasz-galka/ngx-gallery#158]
Hi,
     this is a great plugin..
     it works great in mozilla and safari,
     but in chrome the page strucks to load image..

please help soon..

**Comment by german-e-mas** [comment]
I'm using Chrome as my main browser and I'm not experiencing any issue. Can you describe your problem to see if it might be happening to us?

**Comment by vignesh007vicky** [comment]
HI @german-e-mas 

I have uplodaed 20 images  from admin panel, that is done.
after that i call the image url and assinging 
`                     this.galleryOptions =[
{ "image": false, "height": "100px","width": "100%","thumbnailsColumns": 10,"thumbnailsMargin": 10, "thumbnailMargin": 10 , "thumbnailsMoveSize": 5 },
{ "breakpoint": 500, "width": "100%"  }
]`

`if(this.eventId.gallery){
     for(var i=0;i<this.eventId.gallery.length;i++)
             {
             this.galleryImages[i] = {
               small:this.url+'images/event-gallery/'+this.eventId.gallery[i]._id+'_'+this.eventId.gallery[i].imageName, 
             medium : this.url+'images/event-gallery/'+this.eventId.gallery[i]._id+'_'+this.eventId.gallery[i].imageName,
             big : this.url+'images/event-gallery/'+this.eventId.gallery[i]._id+'_'+this.eventId.gallery[i].imageName,
             description:this.eventId.gallery[i].content
             }
           }
           this.loading = false;
         }`

this is what im doing
it is working great in safari and mozilla

but in chrome in mac, ubuntu and windows the browser hangs very much

already three youtube iframes are loading in that component.


please help..

**Comment by vignesh007vicky** [comment]
HI @german-e-mas 

I have uplodaed 20 images  from admin panel, that is done.
after that i call the image url and assinging 
`                     this.galleryOptions =[
{ "image": false, "height": "100px","width": "100%","thumbnailsColumns": 10,"thumbnailsMargin": 10, "thumbnailMargin": 10 , "thumbnailsMoveSize": 5 },
{ "breakpoint": 500, "width": "100%"  }
]`

`if(this.eventId.gallery){
     for(var i=0;i<this.eventId.gallery.length;i++)
             {
             this.galleryImages[i] = {
               small:this.url+'images/event-gallery/'+this.eventId.gallery[i]._id+'_'+this.eventId.gallery[i].imageName, 
             medium : this.url+'images/event-gallery/'+this.eventId.gallery[i]._id+'_'+this.eventId.gallery[i].imageName,
             big : this.url+'images/event-gallery/'+this.eventId.gallery[i]._id+'_'+this.eventId.gallery[i].imageName,
             description:this.eventId.gallery[i].content
             }
           }
           this.loading = false;
         }`

this is what im doing
it is working great in safari and mozilla

but in chrome in mac, ubuntu and windows the browser hangs very much

already three youtube iframes are loading in that component.


please help..

**Comment by vignesh007vicky** [comment]
??
