### ISSUE TITLE
it is possible to show only thumbnails with its description?

### ISSUE THREAD

**Issue by carloscercado** [lukasz-galka/ngx-gallery#159]
I can to show only thumbnails using this code:
``[
{ "image": false, 
"thumbnailsRemainingCount": true,
 "height": "100px" }
{ "breakpoint": 500, 
"width": "100%",
 "thumbnailsColumns": 2 }
] ``
I want to show the description of each image too.... it is possibble?

**Comment by lukasz-galka** [comment]
@carloscercado you can have description only for image https://lukasz-galka.github.io/ngx-gallery-demo/#image-with-description and for preview https://lukasz-galka.github.io/ngx-gallery-demo/#preview-with-image-description-and-fullscreen

**Comment by carloscercado** [comment]
@lukasz-galka i can to  show the description in the thumbnails  section?
