### ISSUE TITLE
How can I use show method?

### ISSUE THREAD

**Issue by azinramezani** [lukasz-galka/ngx-gallery#160]
Hi,

I want to jump to a specific index by clicking a button. I can see in API we have "show" method but I don't know how can I call that method?

Or is there a better way to change the index of current image?

Thanks,
Azin

**Comment by lukasz-galka** [comment]
@azinramezani here you have an example https://github.com/lukasz-galka/ngx-gallery/issues/50

**Comment by azinramezani** [comment]
@lukasz-galka  thank you very much for your reply.
How can I access that "gallery" object in my component .ts file?

**Comment by lukasz-galka** [comment]
@azinramezani https://github.com/lukasz-galka/ngx-gallery/issues/20
