### ISSUE TITLE
want to add styling to description of images 

### ISSUE THREAD

**Issue by lobnazakaria** [lukasz-galka/ngx-gallery#161]
is it possible to add styling to description ?
i added html tags and it worked but i couldn't add styling to it

**Comment by lukasz-galka** [comment]
@lobnazakaria 

for image
```
ngx-gallery /deep/ .ngx-gallery-image-text {
  background: red;
}
```

for preview
```
ngx-gallery /deep/ .ngx-gallery-preview-text {
  background: red;
}
```

**Comment by tadkim** [comment]
is it possible to set style to each description?

ngx-gallery /deep/ .ngx-gallery-image-text {
  background: red;
 &:nth-of-type(1){ color: gold; }
 &:nth-of-type(2){ color: yellow; }
 &:nth-of-type(3){ color: green; }
//...
}
