### ISSUE TITLE
Gallery Component inside ngFor loop

### ISSUE THREAD

**Issue by Omi0** [lukasz-galka/ngx-gallery#162]
I tried to get it working inside the loop. Did the following:
`<div *ngFor="let product of products">
                <ngx-gallery *ngIf="product.images.length > 0" [options]="galleryOptions" [images]="getGalleryImages(product.images)"></ngx-gallery>
        </div>`

`getGalleryImages(images: IFile[]): NgxGalleryImage[] {
    let galleryImages: NgxGalleryImage[] = [];
    images.forEach(image => {
      galleryImages.push({
        small: image,
        medium: image,
        big: image
      });
    });
    return galleryImages;
  }`

Gallery displayed, Images populated, but its is just keep going and going... If you add console.log inside getGalleryImages method you'll see that it executes every time I hover cursor above the gallery. Is there a way to sort it out?

**Comment by Bodeclas** [comment]
Hello @Omi0, you can create a child component for your ngx-gallery. For example:

```parent-component.html
<!-- parent-component.html -->
<some-tag>
 <child-component *ngFor="let product of products" [product]="product"></child-component>
</some-tag>
```

```child-component.html
<!-- child-component.html -->
<some-tag>
 <ngx-gallery [images]="galleryImages"></ngx-gallery>
</some-tag>
```

```child-component.ts

// child-component.ts

import { NgxGalleryImage } from 'ngx-gallery';

export class ChildComponent implements OnInit {
@Input() product: Product;

galleryImages: NgxGalleryImage[] = [];

ngOnInit(): void {
    this.galleryImages = [
      { small: this.product.image.url, medium: this.product.image.url, big: this.product.image.url }
    ];
  }
...
```
