### ISSUE TITLE
Multiple gallery instances on one page causes keydown madness

### ISSUE THREAD

**Issue by JakubEsterka** [lukasz-galka/ngx-gallery#169]
I have about 20 gallery components in DOM rendered - each one adds its own keydown listeners. This means that writing anything in any input is really slow. I tried disabling keyboard options, but listeners are still added to window.

Is there any way how could I disable it completely? Or I have to make my own gallery component without adding those listeners.

Thanks a lot!

**Comment by JakubEsterka** [comment]
I just commented out the host listener in compiled gallery - but maybe its worth solving anyway.

**Comment by lukasz-galka** [comment]
Hi @JakubEsterka, you are right.

**Comment by lukasz-galka** [comment]
Fixed in `5.4.1`
