### ISSUE TITLE
How can i get an image?

### ISSUE THREAD

**Issue by avvie** [lukasz-galka/ngx-gallery#17]
I am new to angular development. I am trying to figure in your code, if there is a way to get the index and the images array. or an onclick event that can return me the image object of the selected image. 

If there is an easy way to do it let me know. If not, please point me towards where i need to add stuff.

btw great work with the gallery!

Looking forward to your reply

**Comment by lukasz-galka** [comment]
Hi @avvie currently there is no option/event for this. I can try to implement this tomorrow.

**Comment by avvie** [comment]
Cheers mate. Let me know when, ill try to look at how you did it for learning as well.. Cause i was searching all. Day to figure out how to get data from something that is inside node_modules

**Comment by avvie** [comment]
I saw you made a commit today, did you manage to implement getting the current selection?

**Comment by lukasz-galka** [comment]
not yet, but I'm working on it

**Comment by lukasz-galka** [comment]
please check version `1.0.3` and event `change`.

Example:
html
`<ngx-gallery [options]="eventsExample.options" [images]="eventsExample.images" (change)="onChange($event)"></ngx-gallery>`

ts
```
onChange(data: any): void {
  console.log(data);
}
```

Demo available here https://lukasz-galka.github.io/ngx-gallery-demo/#events

**Comment by avvie** [comment]
You are a literal god! thanks !! this works great

**Comment by andaniel2029** [comment]
hello, lukasz-galka!

I followed your code.

But my console window didn't appear anything.

<ngx-gallery [options]="eventsExample.options" [images]="eventsExample.images" (change)="onChange($event)"></ngx-gallery>

ts

onChange(data: any): void {
  console.log(data);
}

help me!!!
