### ISSUE TITLE
Preview is overlaid by mat-sidenav

### ISSUE THREAD

**Issue by hpawe01** [lukasz-galka/ngx-gallery#170]
When I use the `MatSidenavModule` from @angular/material2 the fullscreen mode is overlaid by the `mat-sidenav` components and make navigation impossible.

See https://ngx-gallery-sidenav.stackblitz.io for example.

A workaround would be to set the z-index of `mat-sidenav` to `-1` but I don't know if this is the cleanest way to handle this issue.

**Comment by lukasz-galka** [comment]
`mat-sidenav` has `z-index: 2`, `mat-sidenav-content` which contains `ngx-gallery` has `z-index: 1`, because of that preview is under sidenav.

Imo you should listen to `previewOpen` event and set `z-index: 1` on `mat-sidenav`, and of course set previous value on `previewClose`

**Comment by hpawe01** [comment]
Okay, seems reasonable. We don't know where the `ngx-gallery` is used, so it makes no sense to handle this inside the library.
But with the outputs `previewOpen` and `previewClose` this should work.

Thanks for your input!
