### ISSUE TITLE
How do I get the ID of the thumbnails

### ISSUE THREAD

**Issue by morzito** [lukasz-galka/ngx-gallery#171]
How do I get the ID of the thumbnails when I click on it?

I have 2 actions [NgxGalleryAction] on thumbnails (remove img and edit img). When i click on this actions, i can`t get ID of image.

`const deleteAction = new NgxGalleryAction({
      disabled: false,
      icon: 'fa fa-remove',
      titleText: 'Remove image',
      onClick: () => {
           // how get imageId?
      }
    });`

Actions:

`this.galleryOptions = [
      {
        thumbnailActions: [
          deleteAction
        ]
     }]`

**Comment by yangwen2** [comment]
what ID? According to the doc and source, this is the image class;  As  you can see, there is no id property.
class NgxGalleryImage implements INgxGalleryImage {
    small?: string | SafeResourceUrl;
    medium?: string | SafeResourceUrl;
    big?: string | SafeResourceUrl;
    description?: string;
    url?: string;
    constructor(obj: INgxGalleryImage);
}

**Comment by sebafra** [comment]
I used in this way:
`thumbnailActions: [{ icon: 'fa fa-plus', onClick: this.goToURL.bind(this), titleText: 'See More' }]`
and after:
`  goToURL(event, index): void {
    const item = this.galleryImages.splice(index, 1);
  }`
