### ISSUE TITLE
thumbnails position and image preview

### ISSUE THREAD

**Issue by ehsaanwelcome** [lukasz-galka/ngx-gallery#172]
1. Is it possible to add left and right thumbnails layout option?

2. image preview triggered either on thumbnail or image click. Is there any way to disable preview on thumbnail click but only on image click. thumbnail click should change image and image click should show preview.

**Comment by lukasz-galka** [comment]
1. unfortunately no, there is already ticket for that https://github.com/lukasz-galka/ngx-gallery/issues/82
2. I think it is how it works now, click on thumbnail changes image, and click on images opens preview.

I'm closing because of duplication, feel free to open if there is something more
