### ISSUE TITLE
navigation arrows if only one image is in the gallery

### ISSUE THREAD

**Issue by Chris938621** [lukasz-galka/ngx-gallery#173]
Hi Lukasz.
is there a possibility to disable the navigation arrows? In some cases we load the gallery with only one picture and than the arrows are not needed.
Best regards,
Christian

**Comment by german-e-mas** [comment]
I think you can try with `imageArrows: false` in the options.

**Comment by Chris938621** [comment]
Thank you, german-e-mas!
Is there also a possibility to disable the  small preview image in this case?

**Comment by german-e-mas** [comment]
No problem @Chris938621 . You can do that with `thumbnails: false`. I suggest you to read the gallery options of the readme: [NgxGalleryOptions](https://github.com/lukasz-galka/ngx-gallery#ngxgalleryoptions). There are many interesting options in it that can help you.
