### ISSUE TITLE
Fill image row before columns

### ISSUE THREAD

**Issue by mnesser** [lukasz-galka/ngx-gallery#174]
I use a "grid" thumbnailsRows: 6,   thumbnailsColumns: 6. 
If there is less than 18 images I wish to fill the rows first..
Like this.
XXXXXX
XXXXXX
000000
000000
000000
000000
not
XX0000
XX0000
XX0000
XX0000
XX0000
XX0000

X = image,
0 = Empty

**Comment by lukasz-galka** [comment]
@mnesser unfortunately currently there is no option for that ;/ There already is similar issue https://github.com/lukasz-galka/ngx-gallery/issues/116 I will try to add this feature soon.

**Comment by lukasz-galka** [comment]
I'm closing because of duplication
