### ISSUE TITLE
Feature request: hook for custom preview

### ISSUE THREAD

**Issue by arielouziel** [lukasz-galka/ngx-gallery#175]
Hi, 

First of all, thanks for your great job !

I'm developping an app with Ionic, and I'd like to override the preview component of NgxGallery to use ion-slides (better for mobile UX). Unfortunately, there's currently no mean to hook into the 'openPreview' event to override default behavior. 

If I disable preview, I don't receive the event, and if I enable it, I can't prevent the PreviewComponent from showing. 

Would it be possible to add an option { 'previewCustom': boolean } and in the case it's true, fire the event but don't show default component ? 

Thanks !

**Comment by lukasz-galka** [comment]
Hi @arielouziel, thanks for your PR, your change is available in version `5.5.0`

**Comment by arielouziel** [comment]
Great, thank you !

Le mar. 3 juil. 2018 à 07:53, Łukasz Gałka <notifications@github.com> a
écrit :
