### ISSUE TITLE
Mobile swipe

### ISSUE THREAD

**Issue by CarlosTorrecillas** [lukasz-galka/ngx-gallery#177]
Hi there,

First of all the library is great so thanks for that!

I wanted to know whether you could handle the swipe gestures on mobile to go to the next image.

Cheers

**Comment by lukasz-galka** [comment]
Hi @CarlosTorrecillas Have you checked `imageSwipe`, `thumbnailsSwipe` and `previewSwipe`? Also pls check https://github.com/lukasz-galka/ngx-gallery#prerequisites

**Comment by CarlosTorrecillas** [comment]
Hi @lukasz-galka Thanks for this. I have just added hammer.js and enabled the three features to see how it works. Is there any option that could be cancelling that? I cannot get it to work. My options:

```
{
                arrowPrevIcon: 'fa fa-angle-left',
                arrowNextIcon: 'fa fa-angle-right',
                imageAutoPlay: true,
                imageAutoPlayInterval: 4000,
                imageAutoPlayPauseOnHover: true,
                width: '100%',
                height: '725px',
                thumbnailsColumns: 8,
                imageInfinityMove: true,
                previewInfinityMove: true,
                previewCloseOnClick : true,
                imagePercent: 90,
                imageSwipe: true,
                thumbnailsSwipe: true,
                previewSwipe: true,
                thumbnailsPercent: 10,
                thumbnailsMargin: 5,
                thumbnailMargin: 5,
            },
```

**Comment by CarlosTorrecillas** [comment]
All good, it works. Any change you can also enable the transition to get the animation effect of actually passing one slide and getting the other as opposed to the fade in/out effect?

**Comment by lukasz-galka** [comment]
https://lukasz-galka.github.io/ngx-gallery-demo/#animation-slide ?

**Comment by CarlosTorrecillas** [comment]
That's exactly what I was looking for. Is there any chance that the slide animation does not go in the opposite direction when going back to the first slide? Say I'm pressing the right button constantly, when I get to the last one, the animation goes to the opposite direction and the first slide loads again. Would it be possible to configure it to also go in the same direction?

My gallery options for reference:

```
arrowPrevIcon: 'fa fa-angle-left',
                arrowNextIcon: 'fa fa-angle-right',
                imageAutoPlay: true,
                imageAutoPlayInterval: 4000,
                imageAutoPlayPauseOnHover: true,
                imageAnimation: 'slide',
                width: '100%',
                height: '725px',
                thumbnailsColumns: 8,
                imageInfinityMove: true,
                previewInfinityMove: true,
                previewCloseOnClick : true,
                imagePercent: 90,
                imageSwipe: true,
                thumbnailsSwipe: true,
                previewSwipe: true,
                thumbnailsPercent: 10,
                thumbnailsMargin: 5,
                thumbnailMargin: 5,
```

**Comment by lukasz-galka** [comment]
no, there is no option for that.
