### ISSUE TITLE
Options thumbnailsRows and thumbnailsColumns with thumbnailsRemainingCount: true

### ISSUE THREAD

**Issue by Shustoff** [lukasz-galka/ngx-gallery#178]
Hello, I found a bug. 
If I use two options: thumbnailsRows > 1 and thumbnailsColumns > 1 with thumbnailsRemainingCount: true. Then badge 'RemainingCount' visible only in one row (or column), and other thumbnails visible only in one row (or column). Option 'thumbnailsOrder' define an order in this case.

**Comment by lukasz-galka** [comment]
Thanks @Shustoff, fixed in `5.6.1`
