### ISSUE TITLE
Apply 'Contain' To Thumbnails Background-Size?

### ISSUE THREAD

**Issue by TonganJedi** [lukasz-galka/ngx-gallery#18]
First, let me thank you for this excellent carousel.

Do you have any suggestions on how to apply the contain value to the background of the thumbnails? Is that even doable? I have a library of thumbnails that are of inconsistent size (but all of them 120px or less).

CSS is not my forte so any assistance would be appreciated.

**Comment by lukasz-galka** [comment]
HI @TonganJedi please check version `1.0.2` and option `thumbnailSize`, for example `thumbnailSize: NgxGalleryImageSize.Contain`

You can see this in action here 
https://lukasz-galka.github.io/ngx-gallery-demo/#image-size-contain

**Comment by TonganJedi** [comment]
You're a prince among men, sir. Thanks!


Regards,

Lotu Moeloa

**Comment by TonganJedi** [comment]
I updated to 1.0.2, but now I'm receiving an error message:

> node_modules\ngx-gallery\lib\ngx-gallery-helper.service.ts(6,5): error TS2322: Build:Type 'Map<{}, {}>' is not assignable to type 'Map<string, Function[]>'.

Looks like the NgxGalleryHelperService and NgxGalleryComponent classes are unable to find the angular/core module.

Having the same issue with 1.0.3 as well.

**Comment by lukasz-galka** [comment]
Could you paste here your package.json or just dependencies?

**Comment by TonganJedi** [comment]
"dependencies": {
    "@ angular/animations": "4.2.2",
    "@ angular/common": "4.2.2",
    "@ angular/compiler": "4.2.2",
    "@ angular/compiler-cli": "4.2.2",
    "@ angular/core": "4.2.2",
    "@ angular/forms": "4.2.2",
    "@ angular/http": "4.2.2",
    "@ angular/platform-browser": "4.2.2",
    "@ angular/platform-browser-dynamic": "4.2.2",
    "@ angular/platform-server": "4.2.2",
    "@ angular/router": "4.2.2",
    "@ angular/tsc-wrapped": "4.2.2",
    "@ angular/upgrade": "4.2.2",
    "@ ng-bootstrap/ng-bootstrap": "1.0.0-alpha.28",
    "bootstrap": "3.3.7",
    "core-js": "2.4.1",
    "esri-system-js": "1.0.0-beta.0",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "ngx-gallery": "1.0.0",
    "rxjs": "5.4.0",
    "systemjs": "0.19.40",
    "zone.js": "0.8.13"
  },
  "devDependencies": {
    "concurrently": "3.4.0",
    "lite-server": "2.3.0",
    "typescript": "2.4.1",
    "@ types/node": "7.0.7"
 }

**Comment by lukasz-galka** [comment]
I couldn't reproduce this message but I have fixed this line
`node_modules\ngx-gallery\lib\ngx-gallery-helper.service.ts(6,5)
`
Could you check version 1.0.4?

**Comment by TonganJedi** [comment]
Sorry for the delayed response. I updated to 1.0.4 and the original error is gone, but now I see a problem with SystemJS evaluating node_modules/ngx-gallery/bundles/ngx-gallery.umd.js. There appears to be a syntax error.

> Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)

Please let me know what I can provide you to help nail this down. Thanks!

**Comment by TonganJedi** [comment]
This is our systemjs.config file:

(function (global) {

    var map = {
        'app': 'app', // 'dist',
        '@angular': 'node_modules/@angular',
        'rxjs': 'node_modules/rxjs',
        '@ng-bootstrap/ng-bootstrap': 'node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js',
        'ngx-gallery': 'node_modules/ngx-gallery/bundles/ngx-gallery.umd.js'
    };

    var packages = {
        'app': { main: 'main.js', defaultExtension: 'js' },
        'rxjs': { defaultExtension: 'js' }
    };

    var ngPackageNames = [
      'common',
      'compiler',
      'core',
      'forms',
      'http',
      'platform-browser',
      'platform-browser-dynamic',
      'router',
      'upgrade',
    ];

    function packIndex(pkgName) {
        packages['@angular/' + pkgName] = { main: 'index.js', defaultExtension: 'js' };
    }

    function packUmd(pkgName) {
        packages['@angular/' + pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
    }

    var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
    ngPackageNames.forEach(setPackageConfig);

    var config = {
        map: map,
        packages: packages
    };

    System.config(config);

})(this);

**Comment by TonganJedi** [comment]
The console error:

> Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	Evaluating http://localhost:63587/node_modules/ngx-gallery/bundles/ngx-gallery.umd.js
	Error loading http://localhost:63587/app/main.js
	    at eval (<anonymous>)
	Evaluating http://localhost:63587/node_modules/ngx-gallery/bundles/ngx-gallery.umd.js
	Error loading http://localhost:63587/app/main.js
ZoneDelegate.invoke @ zone.js:391

**Comment by TonganJedi** [comment]
IE11 console gave me a bit more information:

![image](https://user-images.githubusercontent.com/30245030/28631131-6f989a3c-71e9-11e7-8cc4-d555b205d9d9.png)

**Comment by lukasz-galka** [comment]
Hi @TonganJedi and sorry for problems with my component. As I can see you are using SystemJS but unfortunately version 1.0.4 is not compatible with SystemJS. Only version 1.0.0 has support for SystemJS. 

In version 1.0.0 I have changed build system (and this build was compatible with SystemJS), but there were problems with AOT build, so I switched back to old build starting from 1.0.1.

Currently I am trying to create build, which will support SystemJS and AOT, but I don't have a lot time lately...

So maybe at this moment you should swtich back to 1.0.0 and I will try to fix build ASAP and let you know.

**Comment by TonganJedi** [comment]
No problem. I'll stay on v.0 until I hear back from you. Thanks!

**Comment by lukasz-galka** [comment]
I'm closing this issue because feature is implemented. There is other task with support for SystemJS https://github.com/lukasz-galka/ngx-gallery/issues/26
