### ISSUE TITLE
Do we have to have 3 different size images? 

### ISSUE THREAD

**Issue by sabeehshah** [lukasz-galka/ngx-gallery#186]
Question

**Comment by german-e-mas** [comment]
https://github.com/lukasz-galka/ngx-gallery#ngxgalleryimage

- small | Type: string | SafeResourceUrl - url used in thumbnails
- medium | Type: string | SafeResourceUrl - url used in image
- big | Type: string | SafeResourceUrl - url used in preview

**Comment by lukasz-galka** [comment]
@sabeehshah yes, you have to set all `small`, `medium` and `big`, but of course you can set the same image for all.
