### ISSUE TITLE
Multi-Touch Zoom with hammer.js's pinch event?

### ISSUE THREAD

**Issue by bb1** [lukasz-galka/ngx-gallery#190]
Woudln't that be a pretty sweet idea?

Since ngx-gallery already uses Hammer.js for swipe it just would be just the logical step to implement gestures for zooming.

**Comment by ASHFAQPATWARI** [comment]
I am currently using this library in ionic based hybrid applications. Pinch Zoom will be the ultimate killer feature.

**Comment by mmsqe** [comment]
pinch event works with CustomHammerConfig, with proper style animation based on continuous zoom change

```
export class CustomHammerConfig extends HammerGestureConfig  {
    overrides = <any>{
        'pinch': { enable: true },
        'rotate': { enable: false }
    };
    options = {
        touchAction: 'pan-y'
    };
}
```

**Comment by bb1** [comment]
> 
> 
> pinch event works with CustomHammerConfig, with proper style animation based on continuous zoom change
> 
> ```
> export class CustomHammerConfig extends HammerGestureConfig  {
>     overrides = <any>{
>         'pinch': { enable: true },
>         'rotate': { enable: false }
>     };
>     options = {
>         touchAction: 'pan-y'
>     };
> }
> ```

But where can I set this? The API doesn't mention this CustomHammerConfig. Did you edited it inside the sourcecode here?

**Comment by mmsqe** [comment]
@bb1 can overwrite `CustomHammerConfig` in `AppModule`, but you need add pinch to zoom logic by yourself since this lib is use zoomStep, sth like

```
onPinch(event) {
    let now = (new Date()).getTime();
    if (event.scale < 1 || event.scale > 3 || now - this.lastZoomedAt < 100) {
        return;
    }

    this.lastZoomedAt = now;
    let img = this.document.querySelector('.ngx-gallery-preview-img-wrapper') as HTMLInputElement;
    let value = 'scale(' + event.scale + ')';
    this.renderer.setStyle(img, 'transform', value);
}
```

**Comment by madmath03** [comment]
Hello @lukasz-galka,

Could this be added directly to the plugin, or at least added in the documentation ?
