### ISSUE TITLE
How to display the thumbnail with same proportions as the original images not square. 

### ISSUE THREAD

**Issue by pamidivenkat** [lukasz-galka/ngx-gallery#196]

**Comment by pamidivenkat** [comment]
![image-sizes](https://user-images.githubusercontent.com/7859972/46143226-f8267700-c276-11e8-9a11-a64d3163f9c9.PNG)

These are 4 different size image, but all are displaying in same height and width.  I need them to display with their original sizes.

**Comment by lukasz-galka** [comment]
Hi @pamidivenkat it is not possible.
