### ISSUE TITLE
Method for moveRight()

### ISSUE THREAD

**Issue by tomcoppensucll** [lukasz-galka/ngx-gallery#197]
Hi,

would it be possible or is it possible to address the method moveRight() on a custom button just as we can access the method showPrev(). So it would be possible to move the thumbnails to the right or left?

Thanks in advance

**Comment by lukasz-galka** [comment]
Hi @tomcoppensucll you can find new methods in version `5.7.0` https://github.com/lukasz-galka/ngx-gallery#methods

**Comment by tomcoppensucll** [comment]
Awesome, thank you!
