### ISSUE TITLE
Change width and height of opened window

### ISSUE THREAD

**Issue by t-zander** [lukasz-galka/ngx-gallery#198]
When opened in modal window for the full screen, the gallery takes size of modal (so in fact it is not full screen)
Is there any way to make opened gallery window full screen, even despite the fact that modal is not full width?
I fixed it with you suggestion for angular material, though I am using bootstrap) ANyway it worked for me.
Another question is, whether I can give fixed size for iamges when thumnail is opened and whether I can style background opacity?
And how can I add own controls? I watched docs but it is not clear...

**Comment by lukasz-galka** [comment]
Hi @t-zander 

you can change background of preview using 
```
ngx-gallery /deep/ ngx-gallery-preview.ngx-gallery-active {
  background: red;
}
```

What do you mean by `own controls`? Do you mean `NgxGalleryAction` ?
