### ISSUE TITLE
Feature Request: Face hover in image preview mode

### ISSUE THREAD

**Issue by wahyuen** [lukasz-galka/ngx-gallery#199]
First off, many thanks for your efforts into this library!

**Scenario:** It would be awesome if when a user displays a fullscreen image, that the library has an ability to draw rectangles on hover/highlight so that people can have an indication of face detection.

I currently have done the processing already to obtain dimensions of where i want to draw the rectangles, however, having issues in attempting to draw a canvas over what is displayed in the lightbox mode currently. 

Example: 
![](https://docs.microsoft.com/en-us/azure/cognitive-services/face/images/getting-started-cs-detected.png)

**Comment by lukasz-galka** [comment]
Hi @wahyuen I think face detection is out of scope of this gallery.
