### ISSUE TITLE
Show all image grid like 10 x 15 images

### ISSUE THREAD

**Issue by premsh** [lukasz-galka/ngx-gallery#20]
I need to create something like this http://oidamo.de/angular2-image-gallery/ but this one uses needs node command to be run before the it works i.e. doesn't work for dynamic images. 

Is there a way to show just all the images as a grid i.e. if I have 150 images, show the grid of 10 x 15? 

If not, is there is a way to invoke the method directly to open the modal? For example if I build custom grid using bootstrap, but when user click the image, invoke the function like `select(5) {` where 5 is index of image clicked. In this case component ngx-gallery will be there, but just hidden. 

**Super urgent, so yes or no question might be extremely helpful.**

**Comment by lukasz-galka** [comment]
Hi @premsh, with my gallery you can build grid, but all images will have the same width and height. You can see grid 1x4 here https://lukasz-galka.github.io/ngx-gallery-demo/#only-thumbnails and gallery with grid 2x3 here https://lukasz-galka.github.io/ngx-gallery-demo/#thumbnails-with-multiple-rows
Using options like thumbnailsRows and thumbnailsColumns you can create grid with any size. However my gallery needs defined size and this can be problematic for you...

Here you can see only modal/preview in action https://lukasz-galka.github.io/ngx-gallery-demo/#only-preview

Example implementation:

```
<button (click)="openPreview()">Open Preview</button>
<ngx-gallery [options]="galleryOptions" [images]="galleryImages" #gallery></ngx-gallery>
```

```
@ViewChild('gallery') gallery: NgxGalleryComponent;
 
ngOnInit(): void {     

	this.galleryOptions = [{
		image: false,
		thumbnails: false,
		width: '0px',
		height: '0px'
	}];
}

openPreview(): void {
    this.gallery.openPreview(0);
}
```

You can pass any index to `this.gallery.openPreview(0);`

**Comment by premsh** [comment]
Thank you @lukasz-galka 

I just happened to be doing exactly same as you were suggested. 

I end up using the bootstrap custom grid to display the images and used the openPreview(index) to invoke the modal carousel. 

Thanks for all the work man! really appreciate it!

**Comment by farzanehp** [comment]
@lukasz-galka Thank you so much, it worked :+1:
