### ISSUE TITLE
Bug - Thumbnails methods

### ISSUE THREAD

**Issue by PaoloSalta** [lukasz-galka/ngx-gallery#200]
I am currently trying to add images to the gallery when the thumbnails component reaches the edge. The problem is that the following methods
- canMoveThumbnailsLeft(): boolean - returns true if you can move thumbnails to left
- canMoveThumbnailsRight(): boolean - returns true if you can move thumbnails to right

do not return a boolean, but a void value.

**Comment by lukasz-galka** [comment]
@PaoloSalta fixed in `5.7.1`
