### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by dalavric** [lukasz-galka/ngx-gallery#201]
Hello I have a problem with the events. None of the events specified in readme work.

<ngx-gallery [options]="galleryOptions" [images]="galleryImages" (onNextClick)="nextClick()" (previewOpen)="onPrevOpen()"></ngx-gallery>

Do i need to do something else or this should be enough for them to get fired?

**Comment by lukasz-galka** [comment]
@dalavric events are listed here https://github.com/lukasz-galka/ngx-gallery#events there is no event `onNextClick`, but `previewOpen` should work

Let me know if you still have issues with events.
