### ISSUE TITLE
Certain images not displaying thumbnails

### ISSUE THREAD

**Issue by mmmatthew** [lukasz-galka/ngx-gallery#202]
I am using ngx-gallery to display images hotlinked from Wikimedia Commons. In certain cases, the images do not show (style is missing) even though the url is valid (e.g. it works for the large preview but not for the thumbnail).

To reproduce:
visit https://beta.water-fountains.org/zurich?lang=en&queryType=byId&database=wikidata&idval=Q27229903
The fountain has many images, but some are only visible in preview mode

The data to display this view can be obtained with this request: 
https://water-fountains.org:3000/api/v1/fountain?queryType=byId&database=wikidata&idval=Q27229903&

**Comment by lukasz-galka** [comment]
@mmmatthew fixed in `5.7.2`
