### ISSUE TITLE
Show thumbnails at the bottom of the preview mode

### ISSUE THREAD

**Issue by yanivps** [lukasz-galka/ngx-gallery#204]
Hi! Thank you for this awesome library!

One thing would make it really perfect which is the ability to show the thumbnails also in the preview mode.
Can you consider supporting this feature or can someone please guide me how to achieve that?

Something like this:
![example](https://i.imgur.com/Lv3nWjt.png)

**Comment by lukasz-galka** [comment]
@yanivps unfortunately this is not possible right now, maybe I will add it but for sure not soon, I'm closing it because there already is a ticket with that https://github.com/lukasz-galka/ngx-gallery/issues/43
