### ISSUE TITLE
Advanced enhancement: Special interactive thumbnail

### ISSUE THREAD

**Issue by mmmatthew** [lukasz-galka/ngx-gallery#212]
This is a special kind of question:
On the following page I would like have the last thumbnail in the gallery be interactive: when the "plus" is clicked, I want to open a Angular modal and not view the image. In other words, when I click the "plus" symbol, I want to get exactly the same behavior as if I click the "contribute" button below. Is there a clever way of doing this?
![image](https://user-images.githubusercontent.com/10126798/48302887-21d3ee80-e503-11e8-977b-4a5667aee8c2.png)
[ >>> LINK <<<](http://localhost:4200/zurich?lang=en&queryType=byId&database=wikidata&idval=Q55170349)

Thanks for any tips!

**Comment by hpawe01** [comment]
You could play around with the [`change` event](https://github.com/lukasz-galka/ngx-gallery#events). When a thumbnail gets selected, you can check, if it was the last one. If yes, jump back one thumbnail (`this.galleryElement.show(currentIndex - 1)`) and call your click method.

**Comment by mmmatthew** [comment]
Thanks for the tip! How do I refer to the gallery element? I tried using
`@ViewChild('gallery') galleryElement: ElementRef;` 
but it doesn't seem to be right

**Comment by hpawe01** [comment]
Try to reference the component:
`@ViewChild('gallery') gallery: NgxGalleryComponent;`

**Comment by mmmatthew** [comment]
Makes sense. Now I have:
component.html
````
<ngx-gallery #gallery
      [options]="galleryOptions"
      [images]="fountain.properties.gallery.value"
      (change)="galleryChangeMonitor()"
      (previewOpen)="setPreviewState('open')"
      (previewClose)="setPreviewState('closed')"></ngx-gallery>
````
with galleryChangeMonitor defined as:
````
galleryChangeMonitor(event){
    console.log('changed:');
    console.log(this.galleryElement.show(0))
  }
````
What I see is that:
- the change event is raised over 500 times when I click the thumbnail or if I click the 'next' arrow
- if I am previewing the images and click the 'next' arrow, the event is not raised

**Comment by mmmatthew** [comment]
Maybe what I want to do is just not reasonable. I will look into other solutions.

**Comment by hpawe01** [comment]
Sorry to hear that. I hope you found another solution. Do you mind, closing this issue than?

**Comment by mmmatthew** [comment]
Sure.
