### ISSUE TITLE
Is there a way to move the arrows outside the images in the gallery?

### ISSUE THREAD

**Issue by sgudigopuram** [lukasz-galka/ngx-gallery#221]
I tried this, but it doesn't work well with the preview.

`ngx-gallery /deep/ .ngx-gallery-arrow-right {
  right: -35px;
}

ngx-gallery /deep/ .ngx-gallery-arrow-left {
  left: -35px;
}`

**Comment by lukasz-galka** [comment]
@sgudigopuram if you don't want to change all arrow you have to be more specific, for example 

```
ngx-gallery /deep/ ngx-gallery-image .ngx-gallery-arrow-right {
  right: -35px;
}

ngx-gallery /deep/ ngx-gallery-image .ngx-gallery-arrow-left {
  left: -35px;
}

```

this changes arrows for `ngx-gallery-image`, you can of course use also `ngx-gallery-thumbnails` to change arrows in thumbnails

**Comment by lukasz-galka** [comment]
@sgudigopuram this is standard html/css, so you can do what do you want :)
