### ISSUE TITLE
How to set action per image/thumbnail

### ISSUE THREAD

**Issue by orenger** [lukasz-galka/ngx-gallery#222]
i am trying to set an action for thumbnail but cant do this.
i want to show pdf/video/img icon on thumbnail so the user will know what type of media is that and therfore the link will be coordinated to the type.
is there a way to do it using this package or i'd have to "implent" the type in my image outside the package?

**Comment by lukasz-galka** [comment]
Hi @orenger  imo you can do it using css

```
ngx-gallery /deep/ .ngx-gallery-thumbnail::after {
  font-family: 'FontAwesome';
  position: absolute;
  top: 5px;
  right: 5px;
  color: white;
}

ngx-gallery /deep/ .ngx-gallery-thumbnail[href$=".jpg"]::after {
  content: '\f042';
}

ngx-gallery /deep/ .ngx-gallery-thumbnail[href$="mp4"]::after {
  content: '\f13d';
}

```

**Comment by orenger** [comment]
Great. worked like a charm
