### ISSUE TITLE
Unable to set closeIcon, arrowPrevIcon .

### ISSUE THREAD

**Issue by pallavikyatham** [lukasz-galka/ngx-gallery#223]
Hi , 
I am using ngx-gallary for previewing images.
galleryOptions=[
{ "arrowNextIcon":"fa fa-arrow-circle-right","arrowPrevIcon":"fa fa-arrow-circle-left","previewCloseOnClick": true, "previewCloseOnEsc": true,"closeIcon" :'fa fa-times-circle',}
]
but close icon, prev and next icons are not displaying. can anyone pls respond asap.

**Comment by lukasz-galka** [comment]
@pallavikyatham Did you install fontawesome? https://github.com/lukasz-galka/ngx-gallery#prerequisites
