### ISSUE TITLE
ng build is not finishing

### ISSUE THREAD

**Issue by rotarypot** [lukasz-galka/ngx-gallery#227]
i am trying to install ngx-gallery on a metronic theme and get this error when building.

`ERROR in node_modules/@ngx-gallery/lightbox/lib/lightbox.animation.d.ts(1,47): error TS1005: ',' expected.`

**Comment by hpawe01** [comment]
I think you are in the wrong GitHub repo. You are using `@ngx-gallery/lightbox` (https://www.npmjs.com/package/@ngx-gallery/lightbox), so you have to report your issue here: https://github.com/murhafsousli/ngx-gallery
