### ISSUE TITLE
Support other icons

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [lukasz-galka/ngx-gallery#23]
Currently this project  support font awesome. Its a great icon library, but doesn't fit each and every design. Its a pity if your project is based on a different icon library (i.e. [Material Icons](https://material.io/icons/), [spectre.css](https://picturepan2.github.io/spectre/elements.html#icons), etc.) that the icons for this project are fixed. 

Most modern icon frameworks depend on using class names for the elements, similar to Font Awesome. Therefor there's not a big point in only supporting Font Awesome. The classnames could be easily passed in a configuration, i.e.:
`nextIconPreview: 'fa fa-arrow-circle-right'`

The current implementation of this project seems to add additional style rules on the existing fa classes, that should be changed (imho) so that the position (and rotation) of the buttons are decoupled from the icons.

**Comment by lukasz-galka** [comment]
Hi @tobi-or-not-tobi, yes, you are right. I will think about it and let you know.

**Comment by tobi-or-not-tobi** [comment]
Ok cool. Let me know if you need help.

**Comment by lukasz-galka** [comment]
Hi @tobi-or-not-tobi, I have added this option in version `1.1.0`, you can see this in action here https://lukasz-galka.github.io/ngx-gallery-demo/#custom-icons
