### ISSUE TITLE
Close on click on overlay

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [lukasz-galka/ngx-gallery#24]
Image galleries are typically navigated by opening an image and quickly closing it by pressing the close button, [pressing ESC](https://github.com/lukasz-galka/ngx-gallery/issues/22) or clicking on the overlay. An option to close the image(preview) is not available AFAIK - correct me if I'm wrong. 

btw: closing on overlay-click is not always preferred, so it could be a config option.

**Comment by lukasz-galka** [comment]
Hi @tobi-or-not-tobi there is already option `previewCloseOnClick`, you can find all available options here https://github.com/lukasz-galka/ngx-gallery#ngxgalleryoptions

**Comment by tobi-or-not-tobi** [comment]
Ah awesome, I must have missed that! Thanks for the prompt reply.
