### ISSUE TITLE
How to add bearer to image ???

### ISSUE THREAD

**Issue by roxic8** [lukasz-galka/ngx-gallery#245]
i have i problem .. in my website api can only access by authorize person who have a token . how to add a token to the galleryimage ???

**Comment by roxic8** [comment]
i have i problem .. in my website api can only access by authorize person who have a token . how to add a token to the galleryimage ???

**Comment by bleuscyther** [comment]
i pass a url parameter on the image with the token,  For the image i have created a different middleware  who takes the  url parameter instead of the bearer.

**Comment by roxic8** [comment]
> i pass a url parameter on the image with the token, For the image i have created a different middleware who takes the url parameter instead of the bearer.

can you show me how you did it ??? or share some code

**Comment by roxic8** [comment]
here's what i did 
his.userService.getImage(this.user.photos[i].url).subscribe(data=> {

            imageurl.push({
                      small: window.URL.createObjectURL(data),
                      medium:  window.URL.createObjectURL(data),
                      big:   window.URL.createObjectURL(data),
                      description:   window.URL.createObjectURL(data),

            })

          },error => {
            console.log(error);
          },() => {

**Comment by german-e-mas** [comment]
What you did makes sense. You need to grab your image using HttpClient, in order to add the Bearer token. The response of that can be a blob. Then, you use this blob to create an Object URL like you did, and display that with the gallery.

Just in case, I also like to call [revokeObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL) on all the gallery images created this way, on the onDestroy lifecycle hook.

**Comment by bleuscyther** [comment]
@roxic8 i addd the token at the end like this:

``` javascript
let img_url = 'http://myimage.com/img.png';
let img_url_with_token = img_url + '?token=' + this.token;
```
It works for the ```src``` element and when i manually need to update the background image.
I did not know about ```createObjectURL()```.

@german-e-mas nice! ... Am i about to do some major refactoring ?  I am about to do it , i hate the 2 api approach. 😔

**Comment by andrejm7** [comment]
@roxic8 
can you help me? I have the same problem .. check this https://github.com/lukasz-galka/ngx-gallery/issues/322#issuecomment-640650407
