### ISSUE TITLE
SEO optimizations for preview mode

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [lukasz-galka/ngx-gallery#25]
In order to improve SEO and site navigation I'd like to have url routing for the zoomed in image. It basically means that whenever you select an image, the URL would change into a unique URL that can be used for navigation (browser history), deeplinks and sharing (i.e. facebook). I'm not sure what the best solution is to achieve this. 

One idea that comes to mind is adding output/inputs that can be used by the outer component to do the routing and select the selected image. That will keep the library clean and focussed on its main task. Something like:
1. image lib loads (default behavior)
2. If the user selects the image an output will be send, so the outer component can navigate and sends the input to the image library (see 3)
3. image lib components checks if there's an input, telling which is the active gallery image. If there's an active image, the image will be selected and the modal shows the image

The output/input would be configurable. 

Interesting to hear your feedback.

**Comment by tobi-or-not-tobi** [comment]
I guess the change event comes into play here. Haven't used it yet.

**Comment by lukasz-galka** [comment]
Hi @tobi-or-not-tobi currently there is `change` event, but this events is only triggered after normal image change (not on preview/modal). I can add additional event, for example `changeOnPreview` which will be triggered on every image change on preview/modal. Let me know.

If you have index you can open preview by hand using `openPreview`, example here https://github.com/lukasz-galka/ngx-gallery/issues/20
