### ISSUE TITLE
image stretch

### ISSUE THREAD

**Issue by cyfrost** [lukasz-galka/ngx-gallery#254]
Hi,

Is there a way to set the image to "Stretched" mode? Currently, it seems the image is "zoomed" or "spanned" across the frame available.

For example, in the `ngx-gallery` tag, it takes options like `width`, `height` and `fullWidth` etc, but is there an option to set the image mode to `Stretched` so that it resizes to fit the frame space available?

Thanks

**Comment by contactsamie** [comment]
Hi @cyfrost  did you get the answer to this?
