### ISSUE TITLE
ngx-gallery without angular-cli 

### ISSUE THREAD

**Issue by danimanrique** [lukasz-galka/ngx-gallery#26]
Hello, I have a problem with the new version. In version 1.0.0 to import the library I indicated the path of the file with the extension "umd.js" in the file systemjs.config.js, but in the new version 1.1.0, this file does not exist and I can not import " Ngx-gallery ".
How should I import the lib? Bearing in mind that I do not use "angular-cli".

**Comment by lukasz-galka** [comment]
Hello @danimanrique, unfortunately only version 1.0.0 has support for SystemJS and has file *umd.js. I have problems with build for project which use angular-cli and for project which not use angualr-cli. I will try to fix this as soon as possible and let you know.

**Comment by danimanrique** [comment]
Ok.. Thanks for the quick reply!

**Comment by lukasz-galka** [comment]
I have added SystemJS support in version `2.0.0`
