### ISSUE TITLE
ngx-gallery with aot build

### ISSUE THREAD

**Issue by bidakh** [lukasz-galka/ngx-gallery#27]
Hi.
I use the component with webpack and AOT build. The scss not working. JIT build is ok.
Can you help me?

**Comment by lukasz-galka** [comment]
Hi @bidakh which version are you using?

**Comment by bidakh** [comment]
latest 1.1.0

**Comment by lukasz-galka** [comment]
Do you have some error?

**Comment by bidakh** [comment]
No error. The problem:
Generated DOM code with JIT (this is good):
[_nghost-c0] {
  display: inline-block; }
  [_nghost-c0]    > *[_ngcontent-c0] {
    float: left; }
  [_nghost-c0]     * {
    box-sizing: border-box; }
  [_nghost-c0]     .ngx-gallery-icon {
    color: white;
    font-size: 25px;
    position: absolute;
    z-index: 2000; }
  [_nghost-c0]     .ngx-gallery-clickable {
    cursor: pointer; }

Generated DOM code with AOT (this is bad):
[_nghost-c0] {
    display: inline-block;

    & > * {
        float: left;
    }

    /deep/ {

        * {
            box-sizing: border-box;
        }

        .ngx-gallery-icon {
            color: white;
            font-size: 25px;
            position: absolute;
            z-index: 2000;
        }

        .ngx-gallery-clickable {
            cursor: pointer;
        }
    }
}

**Comment by bidakh** [comment]
A similar problem here: https://stackoverflow.com/questions/39821948/does-angular-2-ahead-of-time-compiler-support-sass-stylesheets

**Comment by lukasz-galka** [comment]
Could you paste  here packages.json, angular cli version and node version? I am also using aot build for demo page https://lukasz-galka.github.io/ngx-gallery-demo/ and here everything is working fine. I have old angular cli `1.0.0-rc.1`

**Comment by bidakh** [comment]
This is interesting. 
@angular/compiler-cli: 4.1.0     @types/node: 7.0.14
Are you using the webpack? This is my scss loader code part:
  rules: [
    {
      test: /\.ts$/,
      use: ['awesome-typescript-loader', 'angular2-template-loader']
    },
    {
      test: /\.html$/,
      use: 'raw-loader'
    },
    {
      test: /\.(css|scss)$/,
      loaders: ['to-string-loader', 'css-loader', 'sass-loader']
    }
  ]

**Comment by bidakh** [comment]
Sorry, "@angular/compiler-cli": "4.1.0", "@types/node": "7.0.14",

**Comment by bidakh** [comment]
Sorry, angular/common-cli: 4.1.0     types/node: 7.0.14

**Comment by bidakh** [comment]
Sorry, 
angular-cli: 1.0.0-beta.28.3
node: 6.10.0

**Comment by lukasz-galka** [comment]
fixed in `2.0.0`
