### ISSUE TITLE
data:image is not sanitized in preview

### ISSUE THREAD

**Issue by luckynick** [lukasz-galka/ngx-gallery#270]
**BUG REPORT**

**See ngx-gallery-preview.component.ts getSafeUrl() line 275.** 

```
getSafeUrl(image: string): SafeUrl {
    return image.substr(0, 10) === 'data:image' ?
        image : this.sanitization.bypassSecurityTrustUrl(image);
}
```

The condition for sanitizing data:image (base64)  is not correct. 
**Above code makes data:image strings to be returned without sanitazation which is wrong.** 
data:image strings must be sanitized because otherwise Angular will show an error about unsafe value inserted into template and, which is more critical, image will not be shown. 

Problem caused by this bug: 
**Base64 images are not shown in preview.** 
Thumbnail and normal images are shown fine, meaning that there is a problem only in code of preview.

Quick fix for this bug is to force _false_ condition for _image.substr(0, 10)_. See code:
let plainUrl = 'data:image/jpg;base64, /9j/4AAQSkZJRgABA.......';
this.images.push( {small: plainUrl, medium: plainUrl, **big: ' '+plainUrl**} );

**Comment by thhet** [comment]
Had the same problem - thank you very much for the workaround.

**Comment by kolkov** [comment]
Don't understand, what fix is correct? I want to apply this fix in my new `@kolkov/ngx-gallery` repo.
https://github.com/kolkov/ngx-gallery/blob/b424fabd8d256f9c6aef0033cdfdf3f4f2c08295/projects/gallery/src/lib/ngx-gallery-preview/ngx-gallery-preview.component.ts#L262

**Comment by kolkov** [comment]
@luckynick just simple remove this condition?

**Comment by luckynick** [comment]
> @luckynick just simple remove this condition?

Removing the condition and returning only this.sanitization.bypassSecurityTrustUrl(image); would work exactly for case when image has to be sanitized. For other cases, I cannot tell for sure.

**Comment by kolkov** [comment]
@luckynick thanks! Try this version please. https://www.npmjs.com/package/@kolkov/ngx-gallery

**Comment by luckynick** [comment]
> @luckynick thanks! Try this version please. https://www.npmjs.com/package/@kolkov/ngx-gallery

@Kolkov, thank you for your great contribution!
