### ISSUE TITLE
Demos not working | plunker, codepen

### ISSUE THREAD

**Issue by aneeskodappana** [lukasz-galka/ngx-gallery#272]
* https://plnkr.co/edit/D1tdBCeFo6L9tMOCOb9p?p=preview
* https://codepen.io/lukasz-galka/project/editor/XGgxrL

**Both demo shows 404 error on cdn packages**
eg : https://unpkg.com/Observable shows Cannot find package Observable@latest

**Comment by wholypantalones** [comment]
Here's a stackblitz demo I put together since these weren't working. https://stackblitz.com/edit/angular-bf6kvl

**Comment by aneeskodappana** [comment]
@wholypantalones link broken
