### ISSUE TITLE
Easy to click preview mode when slide.

### ISSUE THREAD

**Issue by junimohano** [lukasz-galka/ngx-gallery#28]
Could you fix to run preview mode when I only click not swipe ?

I just tried sliding to see next slide of pictures, but preview is also running.

**Comment by junimohano** [comment]
Also, slide should be only horizontal not vertical.
in terms of mobile, scroll is not working when I touched to scroll down on ngx-gallery.

**Comment by lukasz-galka** [comment]
Hi @junimohano, are you swiping main image or maybe thumbnails? You are right about second comment, could you create separate ticket for that?

**Comment by junimohano** [comment]
okay i will make it

**Comment by junimohano** [comment]
Can you check again for first comment ?

When you swipe, it runs both preview and slide if mouse is up inside of picture,

**Comment by lukasz-galka** [comment]
Hi @junimohano swipe is working fine on touch devices. Do you really need swipe on desktop (using mouse)?

**Comment by junimohano** [comment]
um... then, forget about it...
im gonna use for awhile and then let you know again
thank you
