### ISSUE TITLE
Infinity scroll/slide

### ISSUE THREAD

**Issue by arkhamvm** [lukasz-galka/ngx-gallery#3]
Hi.
How i can to set option to scrolling main/thumb images infinitely?

**Comment by lukasz-galka** [comment]
Hi, currently there is no option for that. I will try to add this as new feature.

**Comment by arkhamvm** [comment]
Ok, thx. i'll be waiting it.

**Comment by lukasz-galka** [comment]
I have added infinity move for image and preview in `1.6.0`
https://lukasz-galka.github.io/ngx-gallery-demo/#infinity-move
