### ISSUE TITLE
Need to upgrade the package.

### ISSUE THREAD

**Issue by Navin-vis** [lukasz-galka/ngx-gallery#308]
Hi,
Get some issue in this package, this package is no compatible with angular 9 please check and upgrade it please
Renderer need to change to Renderer2
And i need force : "enableIvy": false,
And i also need to comment this section
// this.keyDownListener = this.renderer.listenGlobal("window", "keydown", function (e) { return _this.onKeyDown(e); });
Because of this issue this.renderer.listenGlobal is not a function
I attached the ss please find the attachment.
![Issue](https://user-images.githubusercontent.com/58224142/78270171-1c2bde00-7528-11ea-9a1f-74acc67c351d.jpg)

Thanks.

**Comment by kolkov** [comment]
Hi! Try this package please:
https://github.com/kolkov/ngx-gallery

**Comment by Navin-vis** [comment]
Hi,
It worked. I am going to close the issue. 👍 

Thanks.
