### ISSUE TITLE
Angular (10) SSR Support for GalleryOption ImageAutoPlay (loading infinity)

### ISSUE THREAD

**Issue by gitalvininfo** [lukasz-galka/ngx-gallery#332]
Hi!

Currently this does not support Angular SSR when my **galleryOptions imageAutoPlay** is set to **true**. After building the app, white screen is displayed.

```
 this.galleryOptions = [
      {
        thumbnails: false,
        height: "150px",
        width: "100%",
        thumbnailsRows: 1,
        thumbnailsColumns: 1,
        preview: false,
        imageArrows: false,
        // imageAutoPlay: true,
        // imageAutoPlayPauseOnHover: true,
      }
    ];
```

When property **imageAutoPlay** is comment out, I build the app perfectly fine.

Do you have any solutions for this?

Thanks.

**Comment by gitalvininfo** [comment]
My solution 1 is to put the gallery option initialization inside **try catch block.**

```
try {
      const images = [
        { img: "assets/img/landing/image1.svg" },
        { img: "assets/img/landing/image2.svg" }]

      this.galleryImages = [];

      images.map(res => {
        let img = res.img;
        this.galleryImages.push({
          small: img,
          medium: img,
          big: img
        });
      })

      // if (isPlatformBrowser(this.platformId)) {
        this.galleryOptions = [
          {
            thumbnails: false,
            height: "150px",
            width: "100%",
            thumbnailsRows: 1,
            thumbnailsColumns: 1,
            preview: false,
            imageArrows: false,
            imageAutoPlay: true,
            // imageAutoPlayPauseOnHover: true,
          }
        ];
      // }
    }
    catch (e) {
      console.error(e)
    }
```


My solution 2 is to check for platform specific. In Angular we have **isPlatformBrowser** and **isPlatformServer**
Put the gallery option initialization **inside the isPlatformBrowser**

Put this inside your constructor
`@Inject(PLATFORM_ID) private platformId: object`


```
if (isPlatformBrowser(this.platformId)) {
  this.galleryOptions = [
    {
      thumbnails: false,
      height: "150px",
      width: "100%",
      thumbnailsRows: 1,
      thumbnailsColumns: 1,
      preview: false,
      imageArrows: false,
      imageAutoPlay: true,
      // imageAutoPlayPauseOnHover: true,
    }
  ];
 }
```



Since angular ssr is rendering page in server, **solution 2 is not advisable** because it defeats the purpose of server side rendering, it waits for the browser to render the page and not on the server but still fix the loading infinity.

**Comment by csabe812** [comment]
> My solution 1 is to put the gallery option initialization inside **try catch block.**
> 
> ```
> try {
>       const images = [
>         { img: "assets/img/landing/image1.svg" },
>         { img: "assets/img/landing/image2.svg" }]
> 
>       this.galleryImages = [];
> 
>       images.map(res => {
>         let img = res.img;
>         this.galleryImages.push({
>           small: img,
>           medium: img,
>           big: img
>         });
>       })
> 
>       // if (isPlatformBrowser(this.platformId)) {
>         this.galleryOptions = [
>           {
>             thumbnails: false,
>             height: "150px",
>             width: "100%",
>             thumbnailsRows: 1,
>             thumbnailsColumns: 1,
>             preview: false,
>             imageArrows: false,
>             imageAutoPlay: true,
>             // imageAutoPlayPauseOnHover: true,
>           }
>         ];
>       // }
>     }
>     catch (e) {
>       console.error(e)
>     }
> ```
> 
> My solution 2 is to check for platform specific. In Angular we have **isPlatformBrowser** and **isPlatformServer** Put the gallery option initialization **inside the isPlatformBrowser**
> 
> Put this inside your constructor `@Inject(PLATFORM_ID) private platformId: object`
> 
> ```
> if (isPlatformBrowser(this.platformId)) {
>   this.galleryOptions = [
>     {
>       thumbnails: false,
>       height: "150px",
>       width: "100%",
>       thumbnailsRows: 1,
>       thumbnailsColumns: 1,
>       preview: false,
>       imageArrows: false,
>       imageAutoPlay: true,
>       // imageAutoPlayPauseOnHover: true,
>     }
>   ];
>  }
> ```
> 
> Since angular ssr is rendering page in server, **solution 2 is not advisable** because it defeats the purpose of server side rendering, it waits for the browser to render the page and not on the server but still fix the loading infinity.

Hi!

Tried solution1 but did not work for me. In fact a fill the galleryImages variable outside of the try-catch block. Have you found any reasonable solution to these problems?

Of course commenting out of these autoplay settings solve the problem.

Thanks.
