### ISSUE TITLE
 image mode on the phone

### ISSUE THREAD

**Issue by BlankHrt** [lukasz-galka/ngx-gallery#37]
when click image to see image mode on the phone, it loads image in the middle of the screen ,that means i can not see image until i scroll it down.

**Comment by lukasz-galka** [comment]
I have checked on my phone and it is working fine. 

Do you have the same situation with my examples? https://lukasz-galka.github.io/ngx-gallery-demo/#simple-gallery

Are you using Angular Material?

**Comment by BlankHrt** [comment]
i add .mat-card-content to the style.css.
problem still exist

**Comment by lukasz-galka** [comment]
@BlankHrt  I have created simple example with `md-card` and gallery is working fine. 

1. Do you have this issue only on phone or also on desktop?
2. Is gallery working fine if is outside `md-content`?
3. Which version of angular material / angular are you using?

Maybe you can create simple github repository with your issue?
