### ISSUE TITLE
Is it possible to incorporate index in the Images array ?

### ISSUE THREAD

**Issue by SiddharthSh** [lukasz-galka/ngx-gallery#38]
Thanks for the great Repo, just a  suggestion if its possible to incorporate index in the Images array to load the default image on that particular index and not the first one always ?

**Comment by lukasz-galka** [comment]
I have added option `startIndex` in version `1.2.0`.  You can see it in action here https://lukasz-galka.github.io/ngx-gallery-demo/#custom-start-index
