### ISSUE TITLE
angular universal

### ISSUE THREAD

**Issue by BlankHrt** [lukasz-galka/ngx-gallery#39]
it not support angular universal

Error: Cannot find module 'ngx-gallery'

**Comment by lukasz-galka** [comment]
Hi @BlankHrt, could you give me more info? Maybe example project? I am not familiar with angular universal.

**Comment by BlankHrt** [comment]
hi , look at this tutorial 
https://coursetro.com/posts/code/68/Make-your-Angular-App-SEO-Friendly-(Angular-4-+-Universal)
then install universal

**Comment by lukasz-galka** [comment]
Hi @BlankHrt 

As I read here https://github.com/angular/universal-starter 

> For the server bundle you may need to include your 3rd party module into nodeExternals whitelist

you have to include my gallery in `nodeExternals`. 

In repository from your link is also issue `Unable to use any third party library` https://github.com/designcourse/angular-seo/issues/3#issuecomment-313346304 and here is also `nodeExternals`

Unforunatelly in your example there is no `webpack.config`, so I'm not sure how to do it.

Did you add other third part libraries with success? I tried to add angular material but without success.

**Comment by BlankHrt** [comment]
I just put your lib into my shared/lib to solve the problem.
you met unexpected import problem? 
this is my repo https://github.com/BlankHrt/activity .
 it's ok with angular material,jquery in universal
