### ISSUE TITLE
¿How can i load images from a server? Async

### ISSUE THREAD

**Issue by pqzada** [lukasz-galka/ngx-gallery#4]
I'm trying to load images from another server vía service, but i cant.
Is there any way to do this?

**Comment by lukasz-galka** [comment]
Do you have some error? Could you give code example?

**Comment by pqzada** [comment]
Yes, this is the error.

> EXCEPTION: Uncaught (in promise): Error: Error in ./FichaComponent class FichaComponent - inline template:8:38 caused by: Cannot read property 'map' of undefined
Error: Error in ./FichaComponent class FichaComponent - inline template:8:38 caused by: Cannot read property 'map' of undefined

The component code is this:

```
import { Component, OnInit } from '@angular/core';
import { ParametrosService } from './../../servicios/parametros.service';
import { ElasticService } from './../../servicios/elastic.service';

import { NgxGalleryOptions, NgxGalleryImage, NgxGalleryAnimation } from 'ngx-gallery';

@Component({
  selector: 'app-ficha',
  templateUrl: './ficha.component.html',
  styleUrls: ['./ficha.component.css']
})
export class FichaComponent implements OnInit {

  doc = {
    thumbnail: '',
    imagenes: [],
    tipopropiedad: '',
    operacion: '',
    ubicacion: '',
    moneda: '',
    precioCLP: '',
    precioUF: '',
    dormitorios: '3',
    banos: '2',
    m2_construidos: '100',
    m2_terreno: '100',
    descripcion: ''
  };
  titulo = '';
  parametros = { operacion: '', tipo: '', ubicacion: '', id: '', nombre: ''};

  galOpt: NgxGalleryOptions[];
  galImg: NgxGalleryImage[];

  constructor(
    private paramService: ParametrosService,
    private elastic: ElasticService,
  ) {

    this.galOpt = [
      {
        'imageArrows': true,
        'imageSwipe': true,
        'thumbnailsArrows': true,
        'thumbnailsSwipe': true,
        'previewSwipe': true,
        'thumbnailsMargin': 0,
        'thumbnailMargin': 0,
        'thumbnailsColumns': 6,
        'width': '100%',
        'height': '450px',
      }
    ];

    this.obtenerData();

  }

  ngOnInit() {

  }

  obtenerData() {
    this.elastic.obtenerDocumento(this.parametros.id).then(documento => {
      this.doc = documento;
      this.generarTitulo();
      this.doc.imagenes.forEach(imagen => {
        this.galImg.push({
          'small': imagen,
          'medium': imagen,
          'big': imagen
        });
      });
    });
  }

}
```

And the template line is

`<ngx-gallery [options]="galOpt" [images]="galImg"></ngx-gallery>`

I know that the problem is caused because when the gallery is created the galleryImages is undefined. But, i don't know how to make it work, because the images i need to use are the result of the elastic service call.

**Comment by lukasz-galka** [comment]
Hi, you have two options

1. Validate galImg with *ngIf
`<ngx-gallery *ngIf="galImg && galImg.length" [options]="galOpt" [images]="galImg"></ngx-gallery>`

2. Write resolver as decribed here https://blog.thoughtram.io/angular/2016/10/10/resolving-route-data-in-angular-2.html#resolvers-with-dependencies

If you have any problems let me know.

**Comment by lukasz-galka** [comment]
I fixed this issue https://github.com/lukasz-galka/ngx-gallery/issues/6 in version 0.8.1 and this should fix also your issue.

**Comment by pqzada** [comment]
Thanks you man! I implement the solution posted in the issue #6 and work!
Thanks a lot!
