### ISSUE TITLE
ngx-gallery on Angular4

### ISSUE THREAD

**Issue by JurijZ** [lukasz-galka/ngx-gallery#40]
Hi,

Tried to install (npm install ngx-gallery --save) into the project with the following versions of angular:
`"@angular/common": "4.1.2", 
"@angular/compiler": "4.1.2",
"@angular/core": "4.1.2", .....`

It complained with the following error:
**+-- UNMET PEER DEPENDENCY @angular/common@4.1.2
+-- UNMET PEER DEPENDENCY @angular/core@4.1.2
`-- ngx-gallery@1.3.0**

Am I right assuming that the **ngx-gallery** is compatible only with Angular 2?

**Comment by lukasz-galka** [comment]
Hi @JurijZ my lib is working fine with angular 4. I have just created project with 

```
@angular/cli: 1.4.2
node: 8.4.0
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4
```

and is working fine. In my opinion this `UNMET PEER DEPENDENCY` is just worning, gallery should work properly - if is not please let me know.
