### ISSUE TITLE
Override Component CSS Class Z-Index

### ISSUE THREAD

**Issue by TonganJedi** [lukasz-galka/ngx-gallery#44]
The _.ngx-gallery-image.ngx-gallery-active_ CSS class sets the preview image div to a z-index of 1000. Unfortunately, another third-party library we're using also sets their look-ahead search component to the same index and in the collision the search dropdown loses. It needs to win so I need to either reduce or eliminate this property altogether.

Any suggestions on how to override this class?

**Comment by lukasz-galka** [comment]
you have to put this in your component scss/css

```
ngx-gallery /deep/ .ngx-gallery-image.ngx-gallery-active {
    z-index: 10;
}
```

**Comment by TonganJedi** [comment]
![image](https://user-images.githubusercontent.com/30245030/31024962-f8c61a40-a4fd-11e7-9e38-7081380977eb.png)

I tried this, but it doesn't appear to change anything. The z-index property remains at 1000, though I am able to confirm removal of the property fixes the problem.

**Comment by TonganJedi** [comment]
Oddly, setting the property to "initial" or removing it entirely works, but setting it to any number does not. I can test this in Chrome dev tools, but I can't seem to get any css changes in the component to propagate to the DOM.

**Comment by TonganJedi** [comment]
Got it! I had to add the !important property to get the override to kick in. Not ideal, but it works like a charm now. Thanks.
