### ISSUE TITLE
Unexpected value 'undefined' exported by the module 'NgxGalleryModule'

### ISSUE THREAD

**Issue by mayordwells** [lukasz-galka/ngx-gallery#45]
I got this on an Angular 4.4.3 app. ngx-gallery@1.6.1

Any idea what the fix for this would be?

Uncaught Error: Unexpected value 'undefined' exported by the module 'NgxGalleryModule'
    at syntaxError (compiler.es5.js?524d:1694)
    at eval (compiler.es5.js?524d:15556)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js?524d:15554)
    at CompileMetadataResolver.getNgModuleSummary (compiler.es5.js?524d:15467)
    at eval (compiler.es5.js?524d:15540)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js?524d:15525)
    at JitCompiler._loadModules (compiler.es5.js?524d:26958)
    at JitCompiler._compileModuleAndComponents (compiler.es5.js?524d:26931)
syntaxError @ compiler.es5.js?524d:1694
(anonymous) @ compiler.es5.js?524d:15556
CompileMetadataResolver.getNgModuleMetadata @ compiler.es5.js?524d:15554
CompileMetadataResolver.getNgModuleSummary @ compiler.es5.js?524d:15467
(anonymous) @ compiler.es5.js?524d:15540
CompileMetadataResolver.getNgModuleMetadata @ compiler.es5.js?524d:15525
JitCompiler._loadModules @ compiler.es5.js?524d:26958
JitCompiler._compileModuleAndComponents @ compiler.es5.js?524d:26931
JitCompiler.compileModuleAsync @ compiler.es5.js?524d:26860
PlatformRef_._bootstrapModuleWithZone @ core.es5.js?de3d:4536
PlatformRef_.bootstrapModule @ core.es5.js?de3d:4522
(anonymous) @ index.ts?c69e:4
(anonymous) @ main.js:3770
__webpack_require__ @ main.js:20
(anonymous) @ main.js?8d23:1
(anonymous) @ main.js:3758
__webpack_require__ @ main.js:20
(anonymous) @ main.js:3746
__webpack_require__ @ main.js:20
(anonymous) @ main.js:63
(anonymous) @ main.js:66

**Comment by lukasz-galka** [comment]
Hi @mayordwells, are you using angular-cli (which version)?

**Comment by lukasz-galka** [comment]
I have checked locally with

```
λ ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.2
node: 8.4.0
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4
```
and works fine. Please give me more info and I will try to help.

**Comment by mayordwells** [comment]
Hi @lukasz-galka I'm using a Rails 5 + Webpacker gem application. 
Typescript version is 2.5.3

**Comment by lukasz-galka** [comment]
Hi @mayordwells, please check version `2.0.0`

**Comment by mayordwells** [comment]
Hi, @lukasz-galka thanks a lot for your quick response and all the time you have spent working on this module. 
I have tested the latest update and everything seems to be working fine, I am very happy that I was patient enough to see this tool work and make use of it in my project. 
Thanks again.
