### ISSUE TITLE
Pause Image Autoplay

### ISSUE THREAD

**Issue by paulstoica** [lukasz-galka/ngx-gallery#46]
Hello,

First, this is a great feature. Thank you for it.

I want to use imageAutoPlay, but I want also to pause it, when I am mouseover the current image, is this possible?

Thank you.
Have a good day,
Paul.

**Comment by lukasz-galka** [comment]
Hi @paulstoica, it is possible starting from version `1.7.0`, you have two new options `imageAutoPlayPauseOnHover` and `previewAutoPlayPauseOnHover`

Example here https://lukasz-galka.github.io/ngx-gallery-demo/#auto-play

**Comment by paulstoica** [comment]
Great, Thank you!
