### ISSUE TITLE
Configure Thumbnail Arrow Interval

### ISSUE THREAD

**Issue by TonganJedi** [lukasz-galka/ngx-gallery#47]
First, let me thank you for getting this fixed for SystemJS.

Is there a way to set the interval on the thumbnail arrows? For example, say I have a five thumbnail row. When I click on the arrow, I'd like it to go to the next five images rather than one at a time. Thoughts?

**Comment by lukasz-galka** [comment]
Hi @TonganJedi, good idea. I will think about this.

**Comment by lukasz-galka** [comment]
Hi @TonganJedi, please check version `2.1.0` and option `thumbnailsMoveSize`. Live demo here https://lukasz-galka.github.io/ngx-gallery-demo/#move-whole-thumbnails-row

**Comment by TonganJedi** [comment]
Works like a charm, sir. Thank you!
