### ISSUE TITLE
Question about Async loading

### ISSUE THREAD

**Issue by bbsxjy** [lukasz-galka/ngx-gallery#49]
Our project is using your great ngx-gallery. When we async images from database by calling apis, small and medium images work well. However, when clicking the preview image(big), the image did show up but the network showing the ngx-gallery component continuously calling the big image url which causes the browser super slow.

The safeResourceUrl for the async image we get is a dataURI: 'data:image/png;base64,iVB...'
Can you help us to resolve this issue?

code sample: 
`
this.serviceCall.subscribe(

        imageData => {

          let blob = new Blob([imageData.blob()], { type: "image/png" });

          let reader = new FileReader();

          reader.onload = (event) => {

            this.imageUrl = reader.result;
            let elem = {
              small: this.imageUrl,
              medium: this.imageUrl,
              big: this.imageUrl
            };

            this.galleryImages.push(elem);
          };
          reader.readAsDataURL(blob);

        },
        (err) => console.log(err)
      );
`

Thanks a lot!

**Comment by lukasz-galka** [comment]
Hi @bbsxjy I couldn't reproducte this issue, but some time ago @ManpreetSingh80 added PR with fix for similar problem. I have added his fix in version `2.0.1`, please let me know if it works.

**Comment by bbsxjy** [comment]
It has been fixed! Thank you so much!
