### ISSUE TITLE
breakpoint destroys settings

### ISSUE THREAD

**Issue by moshecmc** [lukasz-galka/ngx-gallery#5]
Hello,

I've been using your gallery for my project, and it works great!

I've noticed that

      this.galleryOptions = [
          {
             breakpoint: 800
          }
    ];

doesn't work. In fact, when combined with other settings, none of them apply.

**Comment by lukasz-galka** [comment]
Hi, could you give me more info? Maybe some real example?

**Comment by moshecmc** [comment]
Lukasz,       

 this.galleryOptions = [
            {
                breakpoint: 960,
                thumbnailsColumns: 3,
                width: '95%',
                height: '90%'
            },
            {
                width: '52vw',
                height: '90vh',
                thumbnailsColumns: 6,
                thumbnailsRows: 2,
                imageAnimation: NgxGalleryAnimation.Fade,
                imageSize: 'contain',
                imagePercent: 80,
                thumbnailsPercent: 20,
                thumbnailsMargin: 0,
                thumbnailMargin: 1,
                imageArrowsAutoHide: true,
                thumbnailsArrowsAutoHide: true,
                preview: false
            }
        ];

anything less than 960px, the gallery hides when I added width and height to the default settings. When I remove this, the 960 breakpoint settings work, but the gallery doesn't look good on Desktop. I also tried setting multiple breakpoints to no avail.
