### ISSUE TITLE
Handle next and previus events

### ISSUE THREAD

**Issue by aywiix** [lukasz-galka/ngx-gallery#50]
I'm trying to use the gallery but I can't run the next() or Previus() events. Could you tell me please how to use them with angular ?

**Comment by lukasz-galka** [comment]
Hi @aywiix, Could you give me more info?

**Comment by aywiix** [comment]
I am trying to execute the previous() or next() events from javascript.
I have the component running on the project but I need to run the next() and previous() events from my own buttons.

**Comment by lukasz-galka** [comment]
I will try to add this today or tomorrow

**Comment by aywiix** [comment]
OK, then I'll wait for the solution!
Thank you very much @lukasz-galka

**Comment by lukasz-galka** [comment]
@aywiix please check version `2.2.0` and available methods https://github.com/lukasz-galka/ngx-gallery#methods

Here you can see demo https://lukasz-galka.github.io/ngx-gallery-demo/#buttons-navigation

**Comment by aywiix** [comment]
Wow thank you very much @lukasz-galka . Could you give me a small example of how to use the methods? do I have to import and instantiate some service?

**Comment by lukasz-galka** [comment]
@aywiix these methods are in gallery component, so for example you can add reference variable using `#` and then run metods

```
<button (click)="gallery.showPrev()" [disabled]="!gallery.canShowPrev()">Show Prev</button>
<button (click)="gallery.showNext()" [disabled]="!gallery.canShowNext()">Show Next</button>
<ngx-gallery #gallery [options]="galleryOptions" [images]="galleryImages"></ngx-gallery>
```

you can check full example here https://plnkr.co/edit/QAI2sFMtaMpQpfV00aDC?p=preview

**Comment by german-e-mas** [comment]
Thanks for the example @lukasz-galka ! Very clear.

**Comment by aywiix** [comment]
very good! very clear! Thank you @lukasz-galka

**Comment by iivanov90** [comment]
Hello @lukasz-galka , I want to make thumbnails to start from right to left side. I try to use those method: moveThumbnailsRight() but no success. Can you give me example how to do that?
