### ISSUE TITLE
Remaining thumbnails count

### ISSUE THREAD

**Issue by fpmk** [lukasz-galka/ngx-gallery#52]
Hi, thanks for your awesome component.
I have one feature request. Is it possible to add remaining thumbnails count?
For example: I have 10 pics and I configured that I want to see 3 thumbnails. I don't want to show slider arrows for thumbnails, but I want to see how many picts remaining. For this I want to show label "+6" on the last thumbnail. And when i click to last thumbnail modal picture opens. And one more thing, clicking on any thumbnail opens modal image also.
Thank you.

**Comment by lukasz-galka** [comment]
Hi @fpmk, yes it is possible, I will think about it.

**Comment by fpmk** [comment]
Hi, thanks man. It rocks.
