### ISSUE TITLE
Magnify

### ISSUE THREAD

**Issue by chrishandorf** [lukasz-galka/ngx-gallery#53]
This is really an excellent Angular gallery component with very good documentation including integration with Angular-CLI and MaterialDesign.

The one and only feature that would be very nice to have that is absent is a magnify option when in preview mode.  Something similar to https://sachinchoolur.github.io/lightgallery.js/demos/  (click any image then see the Magnify+ and Magnify- options).

**Comment by lukasz-galka** [comment]
Hi @chrishandorf, I will add this to my features/improvements list.

**Comment by lukasz-galka** [comment]
Hi @chrishandorf, please check version `3.0.1` and option `previewZoom`. Demo here https://lukasz-galka.github.io/ngx-gallery-demo/#preview-with-zoom

**Comment by chrishandorf** [comment]
I took a quick look and it looks great!   I will be working on integrating it and testing it on my own site this weekend.  Thank you for the wonderful work.  Where is the beer link?  :)

Chris

**Comment by chrishandorf** [comment]
Hi @lukasz-galka ,
The Zoom option is working great.  Thank you.  I did notice one problem because there are no restrictions on the minimum / maximum amount of zoom.  If you press the Zoom- button enough times the image will eventually disappear.  That makes sense I guess, but if you press it a few more times the image re-appears but now it is upside down and it starts to get Larger every time you press Zoom-.       Maybe there should be options like this: ?
{
  "previewZoom": true,
  "previewZoomMin":  5,    // Zoom- can be pressed up to 5 times
  "previewZoomMax": 3     // Zoom+ can be pressed up to 3 times
}

**Comment by lukasz-galka** [comment]
Hi @chrishandorf , thank you for suggestions. I have added 3 new options in version `3.1.0`:

- `previewZoomStep`
- `previewZoomMax`
- `previewZoomMin`


https://lukasz-galka.github.io/ngx-gallery-demo/#preview-with-zoom

**Comment by imarks-saisudhakar** [comment]
Wow, Great Component, I Would like to Request to you please implement thumbnails slider with images in modal. 

1) Please add image description in code because i am new one to angular.


Regards,
Saisudhakar,
Email:-muvvasaisudhakar@gmail.com
