### ISSUE TITLE
Get Dynamic Gallery Images

### ISSUE THREAD

**Issue by mayordwells** [lukasz-galka/ngx-gallery#54]
Hi @lukasz-galka, 
Can you please help me, I need to clarify, I'm just a bit confused as to
How can we make getting Gallery Images dynamic?
I find myself in a situation where I need to get the URL of images from the database.

Here's what I got:
```
getGalleryImages() {
    this.galleryImages = [
      {
        small: `${product.images.AP.front}`,
        medium: `${product.images.AP.side}`,
        big: `${product.images.AP.back}`
      }
    ]
  }
```
But this definitely doesn't work in the Component file, it's not compiled because TypeScript doesn't recognize what is AP, it returns `undefined` for `AP` except in the template.html like so `{{ product.images.AP.front }}`
How can you help me achieve my goal of making this dynamic, either in the component file or in the template file? 

BTW, here's an example of what my Image Object from the database looks like: 
```
"images": {
      "AP": {
        "side": "http://vendors.blankstyle.com/ap/data/Hi-Res%20Web%20Images/5066bt_sd_mg.jpg",
        "front": "http://vendors.blankstyle.com/ap/data/Hi-Res%20Web%20Images/5066bt_mg.jpg",
        "back": "http://vendors.blankstyle.com/ap/data/Hi-Res%20Web%20Images/5066bt_mg.jpg"
       }
}
```
Thanks in advance for your help and suggestions.

**Comment by lukasz-galka** [comment]
Hi @mayordwells, something like this https://plnkr.co/edit/UF0cv6ncSSUQnnCwQELh?p=preview ?

**Comment by mayordwells** [comment]
Hi @lukasz-galka,
Thanks for your prompt reply and explanation.  
Let's talk about this part - 
```
 let product = {
      "images": {
        "AP": {
          "side": "http://vendors.blankstyle.com/ap/data/Hi-Res%20Web%20Images/5066bt_sd_mg.jpg",
          "front": "http://vendors.blankstyle.com/ap/data/Hi-Res%20Web%20Images/5066bt_mg.jpg",
          "back": "http://vendors.blankstyle.com/ap/data/Hi-Res%20Web%20Images/5066bt_mg.jpg"
        }
      }
    }
```
How do I make getting images for particular products more dynamic? 
Cos just same as it was, this still remains static in a way.
I tried to achieve this by doing it this way in ngOnInit:
For a particular product on the current route, get all the images that belong to that product is what I intend to achieve with this.
I'm trying to do this with ActivatedRoute but I'm still not getting it. 
```
let productImages = {
      'images': this.product.images
    }
    console.log(productImages);
```

But I'm getting undefined for product.images.

**Comment by lukasz-galka** [comment]
I'm not sure if I understand correctly the problem. I have created simple example with dynamic images https://plnkr.co/edit/8fReBi5yfq6zehtLmDY6?p=preview

So at the begining `galleryImages` is empty `[]`. Next you are making request to server for particular product images and now you should just put these images to `galleryImages`. 

In my example I am doing this on button click. 

Let me know, I would like to help.

**Comment by german-e-mas** [comment]
Hi @mayordwells , are you sure you are getting the right data from your service? Once you know that your product isn't undefined, you can use it in the gallery like @lukasz-galka suggested.

**Comment by mayordwells** [comment]
I'm sorry if I sound confusing, but this is the problem. I had to make sure to push this on Heroku so as to make my request and problem clear. 
I have a list of thousands of products, check here - `https://deaninfotech.herokuapp.com/dashboard/ng/search`
Here's what the product Object looks like - `https://deaninfotech.herokuapp.com/products.json`
When you click on each product it takes you to product details page - `https://deaninfotech.herokuapp.com/dashboard/ng/products/1`
where a request is sent to the server to get the remaining pictures belonging to that product. This is where I make use of this plugin `ngx-gallery` 
What is confusing to me now is that according to your examples I'm supposed to find a way to get all those images in the component file before sending it over to the template. But in your examples image objects are being saved right there in the component as static values. 
This definitely might not be a `ngx-gallery` but I could definitely use some help. 
Please help me out, guys. @lukasz-galka and @german-e-mas 

Thanks for taking the time out to even comment and check my issues. God bless.

**Comment by german-e-mas** [comment]
I am doing something similar (at least ideally).

When you say "where a request is sent to the server to get the remaining pictures belonging to that product", are you sure you are getting this information correctly? Are you able to `console.log` your pictures's URL and check they are defined? This should be done on your Details component's `ngOnInit()`.

Once you have your product (and you are able to see the image URLs), you should be able to populate the gallery the same way as you posted in the comment (which is also what @lukasz-galka did in his Plunker).

I can't ejemplify that in a Plunker, sorry about that. I still think that you are on the right track with the Gallery component, you just need your images to display.

**Comment by mayordwells** [comment]
Hi @german-e-mas,

Thanks again. 
I have done as mentioned even before. But I'm still getting the same error as images is undefined.
`ERROR TypeError: Cannot read property 'images' of undefined`
Here's a complete look at my ProductDetailComponent

```
import { Component, OnInit }           from '@angular/core';
import { ActivatedRoute, ParamMap }    from '@angular/router';
import { 
  NgxGalleryOptions, 
  NgxGalleryImage,
  NgxGalleryAnimation } from 'ngx-gallery';
import { Product }                     from '../../model/product.model';
import { ProductService }              from '../../services/product.service';
import 'rxjs/add/operator/switchMap';
import template                        from './product-detail.html';

@Component({
  selector: 'ab-product-detail',
  template: template
})
export class ProductDetailComponent implements OnInit {
  galleryOptions: NgxGalleryOptions[];
  galleryImages: NgxGalleryImage[];
  product: Product;
  products: Product[];

  constructor(
    private productService: ProductService,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.getProductRoute();
    this.getGalleryOptions();
    this.getGalleryImages();
    
    let productImages = {
      'images': this.product.images
    }
    console.log(productImages);
    
  }

  getGalleryOptions() {
    this.galleryOptions = [
      {
        width: '600px',
        height: '400px',
        thumbnailsColumns: 4,
        imageAnimation: NgxGalleryAnimation.Slide
      },
      {
        breakpoint: 800,
        width: '100%',
        height: '600px',
        imagePercent: 80,
        thumbnailsPercent: 20,
        thumbnailsMargin: 20,
        thumbnailMargin: 20
      },
      {
        breakpoint: 400,
        preview: false 
      }
    ]
  }

  getGalleryImages() {
    this.galleryImages = [
      {
        small: ' ',
        medium: ' ',
        big: ' '
      }
    ]
  }

  getProductRoute() {
    this.route.paramMap
      .switchMap((params: ParamMap) => 
        this.productService.getProduct(+params.get('id')))
      .subscribe(product => this.product = product);
  }
} 
```

That one picture that displays on the product detail page is being displayed with this:
```
<img 
        style="height: 400px; width: 350px;" 
        [src]="product.images.AP?.front">
```

What can be wrong with my logic? and why are the images not retrieved from the server in the component file but can be seen in the template?

**Comment by lukasz-galka** [comment]
You have `undefined` in `console.log` because at this moment you don't have product. Your code is like

1. make async request to server for product
2. console.log
3. response from server

It is working in html because Angular is making change detection after every http request. So Angular knows that your response is end and is refreshing html. More here https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html

Imo your code should look
```
  ngOnInit(): void {
    this.getProductRoute();
    this.getGalleryOptions();
    this.galleryImages = [];
  }

  getProductRoute() {
    this.route.paramMap
      .switchMap((params: ParamMap) => 
        this.productService.getProduct(+params.get('id')))
      .subscribe(product => {
          this.product = product;
         
          this.galleryImages = [{
              small: product.images.AP.front,
              medium: product.images.AP.side,
              big: product.images.AP.back
          }]
      );
  }
```

So you should create `galleryImages` array after response from server.

**Comment by mayordwells** [comment]
Hi @lukasz-galka,
Finally, it worked. Thank you very much. Now we have solved the problem with displaying dynamic images by doing exactly as instructed above.

One other issue that popped up right after is the fact that not all objects, as in, products follow the same JSON pattern.
See this example in the template of how I am displaying images of all products on the list. 
  
```
<img 
              [src]="product.images.AP?.front || product.images.SS?.catalog || 
              product.images.AM?.catalog || product.images.AM?.front">
```
As you can see I am using the elvis operator to ask before actually displaying it.
I tried to do the same in the component but it didn't work. 
I also tried the JavaScript ternary operator but didn't work as well. 
Webpack failed to compile. 
Here's what the error looks like on the console:
```
15:53:07 webpack.1 | ERROR in ./app/javascript/main/app/MainProduct/ProductDetail/index.ts
15:53:07 webpack.1 | (71,33): error TS2339: Property 'AP' does not exist on type 'Object'.
15:53:07 webpack.1 | 
15:53:07 webpack.1 | ERROR in ./app/javascript/main/app/MainProduct/ProductDetail/index.ts
15:53:07 webpack.1 | (72,34): error TS2339: Property 'AP' does not exist on type 'Object'.
15:53:07 webpack.1 | 
15:53:07 webpack.1 | ERROR in ./app/javascript/main/app/MainProduct/ProductDetail/index.ts
15:53:07 webpack.1 | (73,31): error TS2339: Property 'AP' does not exist on type 'Object'.
```
What can we do to fix this?

**Comment by mayordwells** [comment]
I was able to filter out some data and just focus on one. 
My service now looks like this 
```
 getProducts(page?: Number): Observable<Product[]> {
    return this.http.get(`${this.productsUrl}?page=${page}`)
                .map((response: Response) => <Product[]>response.json()
                  .filter(<Product>(product) => product.images != null && product.images.AP != null && product.name != null && product.sku.AP != null ))
                .catch(this.handleError);
  }
```

**Comment by lukasz-galka** [comment]
@mayordwells Do you still have problem with webpack? If everything is ok, please close issue.

**Comment by mayordwells** [comment]
Thanks, everything is fine now.

**Comment by SatleRohit** [comment]
Hi, 
 I'm facing similar issue of undefined property. Below is my code:

import { Component, OnInit } from '@angular/core';
import { MyProject } from './my-project.interface';
import { ActivatedRoute } from '@angular/router';
import { MyProjectService } from 'src/services/my-project.service';
import { NgxGalleryOptions, NgxGalleryImage } from 'ngx-gallery';


@Component({
  selector: 'app-my-project',
  templateUrl: './my-project.component.html',
  styleUrls: ['./my-project.component.scss']
})
export class MyProjectComponent implements OnInit {
  myproject: MyProject;
  galleryOptions: NgxGalleryOptions[];
  galleryImages: NgxGalleryImage[];

  constructor(
    private route: ActivatedRoute,
    private myProjectService: MyProjectService,
    ) { }

  ngOnInit() {
    const id = +this.route.snapshot.paramMap.get('id');
    this.myProjectService.getMyProjectById(id).subscribe(x => {
      this.myproject = x[0];
    });
    this.loadGalleryImages();
  }
  loadGalleryImages() {
    console.log(this.myproject);
    this.galleryOptions = [
      { 'thumbnails': false },
      { 'breakpoint': 500, 'width': '100%', 'height': '200px' }
      ];
    this.galleryImages = [
      {
        medium: this.myproject.image[0]
      }
    ];
  }


}

**Comment by dineshadhikari** [comment]
> I'm not sure if I understand correctly the problem. I have created simple example with dynamic images https://plnkr.co/edit/8fReBi5yfq6zehtLmDY6?p=preview
> 
> So at the begining `galleryImages` is empty `[]`. Next you are making request to server for particular product images and now you should just put these images to `galleryImages`.
> 
> In my example I am doing this on button click.
> 
> Let me know, I would like to help.

Thnks you much 🤞👍👍✌
100% works

**Comment by Muhammad-Taimur** [comment]
Hi Everyone, 

I'm new to Angular. I'm trying to make ngx gallery works it does work with i get the images from assets folder.
But when I get the data from backend and call it in galleryImages[] array it didn't work.
Note: I'm getting the data when I do console.log I can see all data.

I did all my research in read all Articles still no luck
Can some please help me.

Below are my codes.

HTML Code:

`<ngx-gallery [options]="galleryOptions" [images]="galleryImages" class="ngx-gallery"></ngx-gallery>`

Component ts code.

```
export class OrderComponent implements OnInit {

public productObject=[];
galleryOptions: NgxGalleryOptions[] ;
galleryImages: NgxGalleryImage[];
newgalleryImages=[]

  constructor(private _productservice:ProductService,) { }

  ngOnInit(): void {

    this.getGalleryOptions();
    this._productservice.getproductId$
    .subscribe((data) => {
      this.productObject = data
      console.log("Yeh Dahsboard se Data Aya "+JSON.stringify(this.productObject))
  })
  }

    getGalleryOptions(){

   this.galleryOptions = [
      {
        width: '600px',
        height: '400px',
        thumbnailsColumns: 4,
        imageAnimation: NgxGalleryAnimation.Slide
      },
      // max-width 800
      {
        breakpoint: 800,
        width: '100%',
        height: '600px',
        imagePercent: 80,
        thumbnailsPercent: 20,
        thumbnailsMargin: 20,
        thumbnailMargin: 20
      },
      // max-width 400
      {
        breakpoint: 400,
        preview: false
      }
    ];  
    this.galleryImages =[{

      small:  'assets/1.jpg',
      medium: 'assets/1.jpg',
      big: 'assets/1.jpg'
      // small: this.productObject.productBlob[0].imagePath, 
      // medium: data.productBlob[0].imagePath,
      //  big: data.productBlob[0].imagePath
    }]

Note: I try this way still not working  
// this.galleryImages = this.newgalleryImages
  }
  getImage(data){
    this.newgalleryImages.push({
      small:  data.productBlob[0].imagePath,
      medium: data.productBlob[0].imagePath,
      big:    data.productBlob[0].imagePath
      })
  }
}
```
When I add my API data in galleryImages[] array nothing is appearing in screen.
But when I call the images from assets folder it does appearing.
Please help
