### ISSUE TITLE
Variable size

### ISSUE THREAD

**Issue by german-e-mas** [lukasz-galka/ngx-gallery#55]
The gallery currently supports breakpoints to show different sizes and options.

Other than these breakpoints, do you think it would be easy for the gallery to fit a container or variable size? I'm using a layout with flexbox, and this could be interesting to see, yet I don't know how complicated it must be internally.

Playing around with the browser tools, I changed the gallery's width to `100%` or `inherit`, but the component stopped showing images.

Let me know what do you think about this. Thanks again for this awesome component!

**Comment by german-e-mas** [comment]
I just saw that we can do `width: '100%'`, which solved my problem. Doing this for the height is most likely very difficult, right?

Feel free to close this issue! :)

**Comment by lukasz-galka** [comment]
Hi @german-e-mas, `height: '100%'` should also work.

**Comment by german-e-mas** [comment]
Thank you @lukasz-galka !
