### ISSUE TITLE
second time open another image not hide loading & opacity 

### ISSUE THREAD

**Issue by jshupptechnologies** [lukasz-galka/ngx-gallery#58]
I am first time click on image that time open & second time click on another image that time not hide loader.
If open first one image again that time work,but not for other ngx-gallery.
 i was check in issue is not hide loader & not set opacity for second ngx-gallery.

can anyone suggest solution for this ?

**Comment by lukasz-galka** [comment]
Hi @jshupptechnologies I know that there is a problem if you have more than one gallery with the same images, but there should not be a problem with one gallery or many galleries with unique images.

> I am first time click on image that time open & second time click on another image that time not hide loader.

Do you have this situation if you are using one gallery? Do you have duplicated images?
Could you reproducte this using plunker? https://plnkr.co/edit/D1tdBCeFo6L9tMOCOb9p?p=preview

**Comment by jshupptechnologies** [comment]
@lukasz-galka  no i not have any duplicate image. all image name is unique. i was check issue with hide loader & view image. Image load properly but loader not hide because of that image not show view.

here code 
.ngx-gallery-preview-img{
opacity:1
}
this need be 0 after loading.

.ngx-gallery-icon.ngx-gallery-spinner{
dipplay:inline-block;
}

this need to be none.

image load but above two css not change because if that not show image.just showing loader.


i wlil try to reproduce issue on plunker.

**Comment by lukasz-galka** [comment]
Hi @jshupptechnologies, please check version 3.1.1 and let me know.

**Comment by jshupptechnologies** [comment]
@lukasz-galka Thank you so much it's fixed now.
