### ISSUE TITLE
Image stretch

### ISSUE THREAD

**Issue by gtzinos** [lukasz-galka/ngx-gallery#60]
Hi guys,

Thanks for your great library. I am adding on the gallery multiple images with different height and i wondering if is it possible to make something like stretch the image view to display all of them with a unique height.

**Comment by lukasz-galka** [comment]
Hi @gtzinos I am not sure if I understand you correctly but you can set `thumbnailsColumns` to images count. So if you for example have 7 images you can set 7 columns and all images will be visible. 

You can also manage how image is positioned in thumbnail using option `thumbnailSize` and `NgxGalleryImageSize`. It works like css `background-size` https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

If above options are not good for you, maybe could you show me example?
