### ISSUE TITLE
Massive picture reload from server on mouse move in preview mode

### ISSUE THREAD

**Issue by euzu** [lukasz-galka/ngx-gallery#61]
When you are in preview mode and move the mouse over the picture, the image is reloaded from the server multiple times. 
I found out that this is related to the `[src]` tag in the template of `ngx-gallery-preview.component.ts`.
I could fix this issue through changing it to `[src]="src"` and changing the assignment in the function `_show()`   to `this.src = this.getSafeUrl(<string>this.images[this.index]);`. I needed to change the variable  declaration to `src: SafeUrl;`

**Comment by lukasz-galka** [comment]
Hi @euzu, I can't reproduce it. Do you have this behaviour on any demo example? https://lukasz-galka.github.io/ngx-gallery-demo/

Could you give me more info, maybe screen from console?

I would like to reproduce it before fixing.

**Comment by euzu** [comment]
i have uploaded a short screen recording.
[https://ufile.io/m7hmo](url)

Your examples are working fine. Something in my setup is triggering this issue?
```
{
        width: '100%',
        height: '100%',
        thumbnailsColumns: 4,
        thumbnailsPercent: 20,
        thumbnailsMargin: 4,
        thumbnailMargin: 4,
        layout: NgxGalleryLayout.ThumbnailsBottom,
        imageAnimation: NgxGalleryAnimation.Slide,
        imageInfinityMove: true,
        previewInfinityMove: true,
        imageSwipe: true,
        previewSwipe: true,
        thumbnailsSwipe:true,
        imageArrowsAutoHide: true,
        previewForceFullscreen: false,
        previewZoom: true,
        arrowPrevIcon: 'fa fa-chevron-left',
        arrowNextIcon: 'fa fa-chevron-right',
        closeIcon: 'fa fa-times',
        thumbnails
      },
      // max-width 800
      {
        breakpoint: 800,
        previewForceFullscreen: true,
      },
      // max-width 400
      {
        breakpoint: 400,
        previewForceFullscreen: true
      }
```
and the picture urls are 
```
 {
      small: this.apiServerPictureUrl + picture.id,
       medium: this.apiServerThumbnailUrl + picture.id,
      big: this.apiServerPictureUrl + picture.id
    };
```

**Comment by lukasz-galka** [comment]
I have created plunker with your options and imo everything is working fine https://plnkr.co/edit/nRN128BF0LIyNy0c5TsU?p=preview. 

1. Could you try with other images? (you can take images from my demo)
2. Are you using angular-cli? 
3. Are you using server side rendering?

**Comment by euzu** [comment]
@lukasz-galka
1) its the same issue with other images.
2) yes i am using angular-cli
3) no i am not using server side rendering.

My setup is:
i have a spring boot application with REST api. Angular connects to this spring application and loads the images from there. The URI look like  http://<myapplication>/files/<uuid-of-the-picture>

**Comment by lukasz-galka** [comment]
Hi @euzu it has to be something with some package version, could you give me output of 
```npm list --depth 0```

I could fix it using you suggestion but I would like to reproduce it to check. Does this bug block you?

**Comment by euzu** [comment]
Hi @lukasz-galka , no it does not block me.
 Here the package list:
```
myproject@0.1.0
├── @angular/animations@4.4.6
├── @angular/cli@1.5.0
├── @angular/common@4.4.6
├── @angular/compiler@4.4.6
├── @angular/compiler-cli@4.4.6
├── @angular/core@4.4.6
├── @angular/forms@4.4.6
├── @angular/platform-browser@4.4.6
├── @angular/platform-browser-dynamic@4.4.6
├── @angular/router@4.4.6
├── @ng-bootstrap/ng-bootstrap@1.0.0-beta.5
├── @ngx-translate/core@8.0.0
├── @ngx-translate/http-loader@2.0.0
├── @types/jasmine@2.6.3
├── @types/jquery@3.2.16
├── @types/node@8.0.53
├── codelyzer@4.0.1
├── core-js@2.5.1
├── font-awesome@4.7.0
├── hammerjs@2.0.8
├── ionicons@3.0.0
├── jasmine-core@2.8.0
├── jasmine-spec-reporter@4.2.1
├── karma@1.7.1
├── karma-chrome-launcher@2.2.0
├── karma-cli@1.0.1
├── karma-coverage-istanbul-reporter@1.3.0
├── karma-jasmine@1.1.0
├── karma-jasmine-html-reporter@0.2.2
├── karma-phantomjs-launcher@1.0.4
├── latest-version@3.1.0
├── lodash@4.17.4
├── ng2-toastr@4.1.2
├── ngx-treeview@1.2.5
├── protractor@5.2.0
├── rxjs@5.5.2
├── ts-node@3.3.0
├── tslint@5.8.0
├── typescript@2.6.1
└── zone.js@0.8.18
```

**Comment by lukasz-galka** [comment]
@euzu I have added your changes in version `3.1.2` https://github.com/lukasz-galka/ngx-gallery/commit/403a61970c8cbc1963ad779c0273175d505fcb5b

**Comment by euzu** [comment]
The fix solves the problem.
Thank you for your effort.
