### ISSUE TITLE
Feature Request: Zoom Icon size & position [mobile]

### ISSUE THREAD

**Issue by bogacg** [lukasz-galka/ngx-gallery#62]
Zoom functionality is well done, however I think icons are small and not in optimal position for mobile usage.

Center position and bigger size would be a better fit when images are open in mobile size, or maybe even better a way to have some selection for position/size of these icons in config.

Pinch zoom is another option, though that one might me more complex to implement. (didn't read your source yet)

Thank you for your effort.

**Comment by lukasz-galka** [comment]
Hi @bogacg, at this moment you can override default styles, for example https://plnkr.co/edit/CtARb6xxrg2qZqGwSj53?p=preview

Is it ok for you or option will be better?

**Comment by bogacg** [comment]
@lukasz-galka That helps, I'd still leave close button to left and rest (zoom in-out icons) center, doing so similar to your example in css might be cumbersome.
Maybe not urgent one but for future this option might be a good addition.

**Comment by lukasz-galka** [comment]
example with button on right https://plnkr.co/edit/ayVMHmGWMHS7zuV4i091?p=preview 
I will think about some config.
