### ISSUE TITLE
Image URL containing parentheses or space is not working

### ISSUE THREAD

**Issue by omar-nassar** [lukasz-galka/ngx-gallery#63]
Providing a URL that contains parenthesis (left or right) to NgxGalleryImage array, making the image to be blank.

**for example:**

```
this.galleryImages.push({
        small: URL/IMAGE_NAME_CONTAINS_PARANTHESIS(small).jpg,
        medium: URL/IMAGE_NAME_CONTAINS_PARANTHESIS(medium).jpeg,
        big:URL/IMAGE_NAME_CONTAINS_PARANTHESIS(big).jpeg
});
```
when using the above block of code, the gallery will show a blank image.

**Edit** - Nov. 21, 2017 - 3:25 PM GMT :

Also if the image name contains a space it is not being handled by the library, so, I have to **encodeURI**(the-image-url-with-name-contains-space) explicitly.

Thanks!

**Comment by german-e-mas** [comment]
Interesting, I saw this problem too, but didn't thought it was this component. Nice catch @omar-nassar

**Comment by lukasz-galka** [comment]
Hi @omar-nassar, please check version `3.1.3`

**Comment by omar-nassar** [comment]
Many thanks @lukasz-galka it is working perfectly now 👍

**Comment by ChRonX13** [comment]
@lukasz-galka i believe this change may have broken links that contain % signs. Using 3.1.3, reference images to Azure Blob storage with a SAS token (that contains % sign) doesn't work. I then dropped back to 3.1.2 and this seemed to fix the problem. Possible regression?

**Comment by lukasz-galka** [comment]
@omar-nassar , @ChRonX13 please check version `3.1.4`. I have removed `encodeURI` and now I'm just replacing spaces with `%20`

**Comment by ChRonX13** [comment]
back to loading ok with 3.1.4...thanks!

**Comment by omar-nassar** [comment]
working fine. Thanks :)
