### ISSUE TITLE
Dynamic images deleting

### ISSUE THREAD

**Issue by aywiix** [lukasz-galka/ngx-gallery#64]
When the component comes to load many images at once, it consumes a lot of browser memory. For this reason I tried to remove some of the first images of the array, in such a way that it releases a little memory. When deleting the images, the component does not update the Thumbnails and it stops showing the images. You can release any function to update the thumbnails after deleting the first elements of the images array?

**Comment by lukasz-galka** [comment]
Hi @aywiix thumbnails should update after images array change, please check https://lukasz-galka.github.io/ngx-gallery-demo/#dynamic-images-change

Also please take a look on https://github.com/lukasz-galka/ngx-gallery/issues/6

If there still is a problem, let me know.

**Comment by aywiix** [comment]
Hello @lukasz-galka   ,
Apologies, My question was not well done. What I wanted to explain, is that when more elements are removed than the amount in the thumbline, the thumline remains empty. it is updated, but remains empty even though there are elements in the image array. What I propose is to release some function to make update and also make a shift to the right of the images so that the thumbline does not remain empty.
greetings and many thanks!

**Comment by aywiix** [comment]
Hello @lukasz-galka 
The only way I found to solve the problem was using

$("ngx-gallery-thumbnails div.ngx-gallery-thumbnails").attr("style", "left: calc(-0% - 0px);");

For what the thumbline make the shift to the right automatically.

**Comment by aywiix** [comment]
I see that the problem with the index is in the function  "validateIndex(): void "

 if (this.order === NgxGalleryOrder.Column) {
            newIndex = Math.floor(this.selectedIndex / this.rows);
        } else {
            newIndex = this.selectedIndex % Math.ceil(this.images.length / this.rows);
        }

because after removing some images from the beginning of the array the index is out of range, but I cant change the index ...

**Comment by lukasz-galka** [comment]
Hi @aywiix I am working on lazy loading and it will be ready probably today, imo this will fix also your issue.

**Comment by lukasz-galka** [comment]
@aywiix please check version `4.0.0`
