### ISSUE TITLE
How to dynamically set the startIndex (Gallery options)  

### ISSUE THREAD

**Issue by Lijojohnka** [lukasz-galka/ngx-gallery#65]
i want to dynamically set the ngx-gallery options  startIndex  when clicking in the images listed in an html and initialize the gallery-images and options every-time in a model with that selected image index .

its only set the startIndex when initializing the ngx-gallery firsly.

             this.galleryOptions  = [
                          {  width: '600px', height: '400px', thumbnailsColumns: 4, "startIndex" : index  }
                          { "thumbnails": false , "startIndex" : index}  ];

**Comment by lukasz-galka** [comment]
Hi @Lijojohnka, Would you like change all images and options after click on image which is not in gallery? For that imo you should use something like https://angular.io/guide/dynamic-component-loader

Or maybe you are trying to just change active image? More info will be useful.

**Comment by Lijojohnka** [comment]
hi @lukasz-galka 

actually i just give same images array but the index will change each time .

**Comment by lukasz-galka** [comment]
Hi @Lijojohnka, options are only for initialization. But you can use method `show` (availabe in version `3.2.0`). Example here https://plnkr.co/edit/zuAZnaGv36e5AKn1aPfr?p=preview
