### ISSUE TITLE
How to solve this and where should I import hammarjs?

### ISSUE THREAD

**Issue by Lijojohnka** [lukasz-galka/ngx-gallery#66]
Error on while serve ...

Uncaught TypeError: Cannot read property 'HammerGestureConfig' of undefined
    at eval (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:1374:19)
    at eval (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:4:3)
    at eval (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:5:2)
    at eval (<anonymous>)
    at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9)
    at Object.../../../../script-loader/index.js!../../../../ngx-gallery/bundles/ngx-gallery.umd.js (ngx-gallery.umd.js?a77f:1)
    at __webpack_require__ (bootstrap 9c131f2476d0485fe041:54)
    at Object.2 (scripts.bundle.js:112)
    at __webpack_require__ (bootstrap 9c131f2476d0485fe041:54)
    at webpackJsonpCallback (bootstrap 9c131f2476d0485fe041:25)

**Comment by lukasz-galka** [comment]
Hi @Lijojohnka 

At first you have to install hammerjs
`npm install hammerjs --save`

and then import in component which is using gallery. You can see example in my demo app:
https://github.com/lukasz-galka/ngx-gallery-demo/blob/master/src/app/app.component.ts

If this is not working please give me more info. You can also create simple app and push to github or use plunker https://plnkr.co/edit/D1tdBCeFo6L9tMOCOb9p?p=preview

**Comment by Lijojohnka** [comment]
Hi  @lukasz-galka 

i had already install hammerjs in project and also import it in component.. but the error still remains,

when i try to re-install it , the below msg is shown in npm ..

D:\sampleApp>npm install hammerjs --save

sampleApp@1.0.0 D:\sampleApp
+-- UNMET PEER DEPENDENCY @angular/common@4.3.6
+-- UNMET PEER DEPENDENCY @angular/core@4.3.6
+-- UNMET PEER DEPENDENCY @angular/forms@4.3.6
+-- UNMET PEER DEPENDENCY firebase-admin@~5.2.1
`-- hammerjs@2.0.8

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'D:\sampleApp\node_modules\ng2-image-gallery\package.json'
npm WARN @angular/cdk@2.0.0-beta.12 requires a peer of @angular/core@~4.4.4 but none was installed.
npm WARN @angular/cdk@2.0.0-beta.12 requires a peer of @angular/common@~4.4.4 but none was installed.
npm WARN @angular/material@2.0.0-beta.12 requires a peer of @angular/core@~4.4.4 but none was installed.
npm WARN @angular/material@2.0.0-beta.12 requires a peer of @angular/common@~4.4.4 but none was installed.
npm WARN @angular/upgrade@2.4.10 requires a peer of @angular/core@2.4.10 but none was installed.
npm WARN @angular/upgrade@2.4.10 requires a peer of @angular/compiler@2.4.10 but none was installed.
npm WARN @angular/upgrade@2.4.10 requires a peer of @angular/platform-browser@2.4.10 but none was installed.
npm WARN @angular/upgrade@2.4.10 requires a peer of @angular/platform-browser-dynamic@2.4.10 but none was installed.
npm WARN angular2-google-maps@0.17.0 requires a peer of @angular/common@^2.3.1 but none was installed.
npm WARN angular2-google-maps@0.17.0 requires a peer of @angular/core@^2.3.1 but none was installed.
npm WARN @angular/compiler@2.4.4 requires a peer of @angular/core@2.4.4 but none was installed.
npm WARN @angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.10 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN @angular/platform-browser-dynamic@2.4.10 requires a peer of @angular/compiler@2.4.10 but none was installed.
npm WARN firebase-functions@0.6.3 requires a peer of firebase-admin@~5.2.1 but none was installed.
npm WARN ng2-datepicker@1.8.3 requires a peer of @angular/forms@^2.4.0 but none was installed.

**Comment by lukasz-galka** [comment]
Hi @Lijojohnka, so gallery is working fine and there is problem only with hammerjs?
Could you give me output from `npm list --depth 0`

**Comment by Lijojohnka** [comment]
Gallery is working fine but the touch and gestures are not working .

[New Text Document (2).txt](https://github.com/lukasz-galka/ngx-gallery/files/1501028/New.Text.Document.2.txt)
