### ISSUE TITLE
Possible to emit event when gallery is first loaded

### ISSUE THREAD

**Issue by ChRonX13** [lukasz-galka/ngx-gallery#68]
Currently the gallery component will emit an event when the image has been changed, which is great for reacting to when a user has changed an image they are viewing.

Is there currently a way for us to be notified when the first image has been loaded/selected in a similar fashion?

Perhaps as ```ngx-gallery.component.ts``` performs the call to ```ngDoCheck``` and the length of the image array transitions from 0 to >0, you could emit the ```change``` event?

**Comment by lukasz-galka** [comment]
Hi @ChRonX13, emiting change in this way can cause bugs for other people. Imo there are two options
1) emit other event
2) emit change event, but add additional option for that, something like

**Comment by lukasz-galka** [comment]
Hi @ChRonX13, this change can cause bugs for other people. I can add new event `imagesChange`, is it ok for you? I will trigger this event inside `ngDoCheck`

**Comment by ChRonX13** [comment]
yep not a problem

**Comment by lukasz-galka** [comment]
Hi @ChRonX13 please check version `3.2.0` and event `imagesReady` https://github.com/lukasz-galka/ngx-gallery/commit/c20e35413d2f10f45e021435cce855d1d933c1f5
