### ISSUE TITLE
Lazy loading images should be implemented

### ISSUE THREAD

**Issue by SlimDogs** [lukasz-galka/ngx-gallery#69]
Nice plugin, but sadly it can't handle bigger amount of images... And usually use case for galleries is to contain a lot of photos. Please consider implementing some kind of logic which lazy loads images only on thumbnail slide (+ removing invisible thumbnails...).

Cheers

**Comment by lukasz-galka** [comment]
@SlimDogs true, I will think about it

**Comment by tomscript** [comment]
came here looking for this. glad to see its being considered :)

**Comment by lukasz-galka** [comment]
@SlimDogs @tomscript please check version `4.0.0`
