### ISSUE TITLE
Where should I import hammarjs?

### ISSUE THREAD

**Issue by Ermenymw** [lukasz-galka/ngx-gallery#7]
Hi, Lukasz
   I'm new to Angular2. Where should I add the import "hammerjs";? And do I need to import like:
import { Hammerjs } from 'hammerjs';
   Currently I can make the slide show work, but the hammer gestures and arrows are not applied.

**Comment by Ermenymw** [comment]
I found out the solution to add the hammerjs import to "polyfills.ts" file

**Comment by lukasz-galka** [comment]
Hi, you should import hammerjs in component, which is using gallery.

```
import { Component, OnInit, Inject } from '@angular/core';
import 'hammerjs';
import { NgxGalleryOptions, NgxGalleryImage, 
    NgxGalleryAnimation, NgxGalleryImageSize } from 'ngx-gallery';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
}


```

**Comment by Ermenymw** [comment]
I tried to add this import in component file, it gives error of "invalid character". I think we should import it in "polyfills.ts" file and it works for me.

**Comment by lukasz-galka** [comment]
That is strange, I am putting always in component and it works. Could you show me how are you importing hammerjs in component and error message?
