### ISSUE TITLE
Link on the thumbnails

### ISSUE THREAD

**Issue by creever** [lukasz-galka/ngx-gallery#70]
Hi!
Is there any chance to put different link on each thumbnail? If a user click on one of the thumbnail it should navigate to somewhere else. As I saw there is no "issue" exists something like this.

Thanks you for your help and nice work btw!

**Comment by lukasz-galka** [comment]
Hi @creever please check versions `3.3.0` and option `linkTarget` and `thumbnailsAsLinks`. There is also new field `url` in https://github.com/lukasz-galka/ngx-gallery#ngxgalleryimage

**Comment by nadhir-falta** [comment]
Hi @lukasz-galka the current behavior of the link is to refresh the page when clicked, which kind of kills the whole purpose of the SPA and using Angular.
Is there any plans on revisiting that ?
