### ISSUE TITLE
Z-Index 2000?

### ISSUE THREAD

**Issue by Logic-Bits** [lukasz-galka/ngx-gallery#71]
z-index: 2000;

Messes up alot (eg. Bootstrap NavBar dropdowns).

Does it really need to be that high?

**Comment by lukasz-galka** [comment]
Hi @Logic-Bits, I can't change it now because it can cause errors for others. You can create new stacking context for gallery 

```
ngx-gallery {
  position: relative;
  z-index: 10;
}
```

More here https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

Alternatively you can change 2000 to other value

```
ngx-gallery /deep/ .ngx-gallery-icon {
 z-index: 100;
}
```

**Comment by Logic-Bits** [comment]
Thanks, yes that was what I ended up using. Maybe its a good idea to update it in the next major version. Just an idea.

**Comment by lukasz-galka** [comment]
@Logic-Bits, true :)

**Comment by ggeorgakopoulos** [comment]
What if I have a fixed navbar with `z-index: 100` ?
If I use
```
ngx-gallery {
  position: relative;
  z-index: 10;
}
```
Then even preview will be under the navbar, so a part of the image will be covered (incl the close button)

**Comment by lukasz-galka** [comment]
@ggeorgakopoulos please create new issue, this is closed

**Comment by ggeorgakopoulos** [comment]
@lukasz-galka I would like to apologise for commenting too quickly and opening a closed issue (which as I found out isn't an issue at all)

You'll just have to remember that if you have a fixed navbar you'll have to set to different `z-index`, one for the preview and one for the actual fullscreen view

You can close the issue

**Comment by resuta566** [comment]
> Alternatively you can change 2000 to other value
> 
> ```
> ngx-gallery /deep/ .ngx-gallery-icon {
>  z-index: 100;
> }
> ```
this got me an error

```
./src/app/shop/shop-item/shop-item.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  /deep/ .ngx-gallery-image .ngx-gallery-active {
 ^
      Expected selector.
   ╷
15 │   /deep/ .ngx-gallery-image .ngx-gallery-active{
   │   ^
   ╵
  stdin 15:3  root stylesheet

```
