### ISSUE TITLE
Help with rendering images from a shared location outside of assets.

### ISSUE THREAD

**Issue by VigneshVaidyanathan** [lukasz-galka/ngx-gallery#72]
Hi, 

I am new to Angular4 and I am using this to render a image preview options. The images are present in a shared location which is in a separate drive and I get only the URL. I am not able to access that files because it shows 'Not allowed to load local resource:' error when accessing. I want to know if there is any work around for that or if there is option to set the gallery images with the base64 of the content.
Please help.

**Comment by lukasz-galka** [comment]
Hi @VigneshVaidyanathan you can use base64 images like normal url. If you can open url in browser it should also work in gallery.
