### ISSUE TITLE
image url having small brackets '()' are not rendering.

### ISSUE THREAD

**Issue by kamleshpaliwal-tudip** [lukasz-galka/ngx-gallery#73]
Hi,

I have used ngx-gallery library in my project. Actually whenever there are small brackets in my img src url ngx-gallery library is failing to render that image. For example if my URL is like 'uploads/image-(1).jpeg' than the image is not rendering.Please anyone can provide me help.
Any help is appreciated.
Thanks.

**Comment by lukasz-galka** [comment]
HI @kamleshpaliwal-tudip Which version do you use? Imo this was fixed in version `3.1.4`.

**Comment by lukasz-galka** [comment]
@kamleshpaliwal-tudip you can check current version using 
`npm list view ngx-gallery`

if is smaller please install `3.1.4` or latest and let me know

**Comment by kamleshpaliwal-tudip** [comment]
@lukasz-galka I updated to latest one, now it's working thank you ver much.
