### ISSUE TITLE
How change galleryOptions after ngInit?

### ISSUE THREAD

**Issue by danielfnz** [lukasz-galka/ngx-gallery#74]
Hello, i need to set thumbnailsRows  dynamic after  load data from firebase and change the galleryOptions by length.
How do it? the galleryOptions dont reflesh

@lukasz-galka

**Comment by lukasz-galka** [comment]
Hi @danielfnz you can wait for images (with ngIf) and then initialize gallery, example here https://plnkr.co/edit/m48e9TQclY3Wn9nK2pKN?p=preview

I haved added setTimeout to imitate asyc request to firebase. 

`<ngx-gallery *ngIf="galleryImages" ...`

**Comment by danielfnz** [comment]
Thanks, it's works to me.
