### ISSUE TITLE
how to bind data from JSON response ArrayList to galleryImages list using for loop

### ISSUE THREAD

**Issue by rahulasharm** [lukasz-galka/ngx-gallery#75]
how to bind data/property from JSON response ArrayList to gallery images small, medium and big properties using for loop

**Comment by lukasz-galka** [comment]
Hi @rahulasharm could you show me your code? What is not working? Do you have some error?

**Comment by rahulasharm** [comment]
@lukasz-galka 
this.imageDataPoints  is my dynamic ArrayList, and I want to set the media_url property to  this.galleryImages = [
      {
        small: '',
        medium: '',
        big: '',
      }
    ];
please help me to bind this using for loop or any other solution.

this.imageDataPoints = [
   {
      "user_id":11,
      "media_type":"IMAGE",
      "media_uri":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2Ftemp_photo.png?generation=1512207708761660&alt=media",
      "media_name":"155/temp_photo.png"
   },
   {
      "user_id":43,
      "media_type":"IMAGE",
      "media_uri":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2FKendall%20Jenner.jfif?generation=1511847043169272&alt=media",
      "media_name":"155/Kendall Jenner.jfif"
   },
   {
      "user_id":11,
      "media_type":"IMAGE",
      "media_uri":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2Fmaxres.jpg?generation=1512207530832065&alt=media",
      "media_name":"155/maxres.jpg"
   },
   {
      "user_id":43,
      "media_type":"IMAGE",
      "media_uri":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2Fmaxres.jpg?generation=1511869575663768&alt=media",
      "media_name":"155/maxres.jpg"
   },
   {
      "user_id":11,
      "media_type":"IMAGE",
      "media_uri":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2FFacebook%20Cover%20-%20Untitled.jpg?generation=1512490205942447&alt=media",
      "media_name":"155/Facebook Cover - Untitled.jpg"
   },
   {
      "user_id":43,
      "media_type":"IMAGE",
      "media_uri":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2FKendall%20Jenner.jpg?generation=1511869598503407&alt=media",
      "media_name":"155/Kendall Jenner.jpg"
   }
]

**Comment by rahulasharm** [comment]
i want like this:
 this.imagesData = [
    {
       "small":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2Ftemp_photo.png?generation=1512207708761660&alt=media",
       "medium":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2Ftemp_photo.png?generation=1512207708761660&alt=media",
       "big":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2Ftemp_photo.png?generation=1512207708761660&alt=media"
    },
    {
       "small":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2FKendall%20Jenner.jfif?generation=1511847043169272&alt=media",
       "medium":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2FKendall%20Jenner.jfif?generation=1511847043169272&alt=media",
       "big":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2FKendall%20Jenner.jfif?generation=1511847043169272&alt=media"
    },
    {
       "small":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2Fmaxres.jpg?generation=1512207530832065&alt=media",
       "medium":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2Fmaxres.jpg?generation=1512207530832065&alt=media",
       "big":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2Fmaxres.jpg?generation=1512207530832065&alt=media"
    },
    {
       "small":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2Fmaxres.jpg?generation=1511869575663768&alt=media",
       "medium":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2Fmaxres.jpg?generation=1511869575663768&alt=media",
       "big":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2Fmaxres.jpg?generation=1511869575663768&alt=media"
    },
    {
       "small":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2FFacebook%20Cover%20-%20Untitled.jpg?generation=1512490205942447&alt=media",
       "medium":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2FFacebook%20Cover%20-%20Untitled.jpg?generation=1512490205942447&alt=media",
       "big":"https://www.googleapis.com/download/storage/v1/b/dev_platform_media_ingest/o/155%2FFacebook%20Cover%20-%20Untitled.jpg?generation=1512490205942447&alt=media"
    },
    {
       "small":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2FKendall%20Jenner.jpg?generation=1511869598503407&alt=media",
       "medium":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2FKendall%20Jenner.jpg?generation=1511869598503407&alt=media",
       "big":"https://www.googleapis.com/download/storage/v1/b/dev_platform_ingest_media/o/155%2FKendall%20Jenner.jpg?generation=1511869598503407&alt=media"
    }
 ];

**Comment by german-e-mas** [comment]
This sounds more of a code issue than a Gallery one.
I'd try something like:

```
let newGalleryImages = []
for (const data of this.imageDataPoints) {
  const image = {
    small: data.media_uri,
    medium: data.media_uri,
    big: data.media_uri,
    }
  newGalleryImages.push(image);
}
this.galleryImages = newGalleryImages;
```
Again, I don't think this issue is related to the gallery.
