### ISSUE TITLE
Images are displaying blurry.

### ISSUE THREAD

**Issue by kamleshpaliwal-tudip** [lukasz-galka/ngx-gallery#76]
I have used ngx-gallery library.Actually in thumbnail strip images are rendered beautifully but above thumbnail strip they  are not displaying well actually displaying blurry images. Can you please help me why it is happening?

**Comment by lukasz-galka** [comment]
Hi @kamleshpaliwal-tudip 
1. maybe you are using to big images? 
2. Are images in my demo also blured? https://lukasz-galka.github.io/ngx-gallery-demo/  
3. Could you put your images into plunker demo https://plnkr.co/edit/D1tdBCeFo6L9tMOCOb9p?p=preview ? 

I need example to work on fix.

**Comment by TonganJedi** [comment]
I was having similar issues until I realized my images were being stretched. Check to see if your images are too small for your preview window size.
