### ISSUE TITLE
Sliding should stop when user click on image to preview it

### ISSUE THREAD

**Issue by SlimDogs** [lukasz-galka/ngx-gallery#79]
Hey,

Very good work on the plugin and thanks a lot for the lazyLoading implementation!

I noticed that there is a small issue. If I have:
```js
          imageAutoPlay: true,
          imageAutoPlayInterval: 5000
```
options and I click on one of the  images to open the preview element, it still keeps playing in the background... I suppose ideally autoplay would be paused and resumed once viewer closes the preview.

Cheers

**Comment by lukasz-galka** [comment]
Hi @SlimDogs , please check version `4.1.1`
