### ISSUE TITLE
Bug: Clicking on preview image does not show large image in Firefox "Quantum"

### ISSUE THREAD

**Issue by TonganJedi** [lukasz-galka/ngx-gallery#81]
It appears the gallery HTML is injected into the DOM as expected (verified in console), but the spinner is not going away after the large image is loaded.

**Comment by lukasz-galka** [comment]
Hi @TonganJedi could you give me link to this large image or set in plunker https://plnkr.co/edit/D1tdBCeFo6L9tMOCOb9p?p=preview ?

**Comment by TonganJedi** [comment]
Additional testing has demonstrated this might be a local browser config issue instead. Let's close this for now. Thank you!
