### ISSUE TITLE
Change Images Without Destroying/Re-creating Parent Component

### ISSUE THREAD

**Issue by TonganJedi** [lukasz-galka/ngx-gallery#83]
Is there a way to refresh the carousel with new images and have the carousel reset to the first image without recreating the parent component?

Our app allows users to switch between different search targets: some have associated images, some don't. We need to be able to actively refresh without reloading the parent.

**Comment by TonganJedi** [comment]
I should mention that throwing an empty array at the carousel before re-loading it with new images seems to work, but if the user scrolled the thumbnail bar on one set of images past the range limit on the subsequent image set (say the first set has 20 and the second set has 5), the thumbnail bar does not reset to index 1 and it appears missing (has a negative left style).

**Comment by lukasz-galka** [comment]
@TonganJedi did you try to use method `show` https://github.com/lukasz-galka/ngx-gallery#methods ?
you can set new images and after that just run `show(0);`

**Comment by TonganJedi** [comment]
How do you invoke these methods? They're not methods on either the Image or Options arrays. I tried to look up the code for your Show Prev/Show Next buttons, but all I see is the Options code.

**Comment by german-e-mas** [comment]
@lukasz-galka provided this Plunker when the methods were included: https://plnkr.co/edit/QAI2sFMtaMpQpfV00aDC?p=preview Check the template at the `app.component.ts`

Hope this helps you @TonganJedi

**Comment by german-e-mas** [comment]
I agree though, the `Show code` button in the demo page is not very useful in these cases, as it only shows the gallery options.

**Comment by TonganJedi** [comment]
Thank you very much. That clears things up concerning the buttons. Is there a way to programatically invoke the show method in the component? Or are these methods only accessible in the DOM?

**Comment by TonganJedi** [comment]
`import { Component, Input, OnInit, AfterViewInit, ElementRef, ViewChild } from '@angular/core';`

`@ViewChild("gallery", { read: ElementRef }) gallery: ElementRef;`

`ngAfterViewInit(): void {
        this.gallery.nativeElement.show(0);
    }`

I'm assuming the gallery element has an id of "gallery". It's likely I'm trying to access the element before it exists, so I may need to use a different hook.

**Comment by TonganJedi** [comment]
It doesn't appear that the show method will work in this case. If you scroll right through a large number of thumbnails, then reload the carousel with fewer images, if the view isn't re-initialized the css stays where it was before the carousel was reloaded. The new images are rendered off-screen.

![image](https://user-images.githubusercontent.com/30245030/34059690-387bbe3e-e19d-11e7-8021-fb8d5177cc2d.png)

If I kill the style in the browser tools, the thumbnail row appears as expected.

**Comment by TonganJedi** [comment]
For the time being, I've implemented code that will kill any style attributes in the tag after the carousel is reloaded:

`document.getElementsByClassName('ngx-gallery-thumbnails')[0].removeAttribute('style');`

Any chance you could add a reset on the "left" property when the carousel gets a new array passed to it?

**Comment by lukasz-galka** [comment]
@TonganJedi, yes, I will add this

**Comment by lukasz-galka** [comment]
@TonganJedi fixed in `4.1.2`. Now I reset position to default after every images array change

**Comment by TonganJedi** [comment]
Thank you, sir!


Regards,

Lotu Moeloa
