### ISSUE TITLE
Base64 image for different size with ngx-gallery

### ISSUE THREAD

**Issue by pierre03** [lukasz-galka/ngx-gallery#84]
Hello,
I have one base64 image,  i want to use ngx-gallery to display the same image with different size, can you give me an example, please?
Thank you.

**Comment by lukasz-galka** [comment]
Hi @pierre03 
```
        this.galleryImages = [
            {
                small: 'yourbase64image',
                medium: 'yourbase64image',
                big: 'yourbase64image'
            }
        ];
```

?

**Comment by pierre03** [comment]
Thank you, but how can it work with async observable object?
I have an error: 
`Can not read property 'map' of undefined at NgGalleryComponent.ngOnInit......`

**Comment by german-e-mas** [comment]
@pierre03 , that error was mentioned in this issue: #4 . Perhaps it can help you.

**Comment by pierre03** [comment]
Thank you, i got it, it works with static images. 
But the base64 images cannot be displayed, when i take them from an async answer.

HTML:
```
<div *ngIf="images.length>0">
    <ngx-gallery  [options]="options" [images]="images" ></ngx-gallery>
</div>
```

TS:
```
this.subscription = this.consultService.getApplicationSubject()
      .subscribe((app: Application) => {
        if (app != null && app.candidateList != null) {
          this.images = [
            {
              small: app.dataList[FieldNames.PHOTO_IMAGE],
              medium: app.dataList[FieldNames.PHOTO_IMAGE],
              big: app.dataList[FieldNames.PHOTO_IMAGE]
            }
          ];
        }});
}
```

**Comment by lukasz-galka** [comment]
could you show your issue on plunker? https://plnkr.co/edit/D1tdBCeFo6L9tMOCOb9p?p=preview
you can use `setTimeout` to emulate async function

Do you have any error? Is base64 image work without async function?

**Comment by gmareater** [comment]
i'm trying to solve this problem, Honestly you should provide a working example for this
