### ISSUE TITLE
Small pictures outside of the parent panel

### ISSUE THREAD

**Issue by pierre03** [lukasz-galka/ngx-gallery#85]
Hello,
I want to display some pictures in the left side of the page, but it's always outside of the panel which is in white beakground color. 
Can someone tell me which property should be updated to get the good size, please,

<img width="274" alt="2017-12-19 15_58_26-webapp" src="https://user-images.githubusercontent.com/18083828/34162954-b6816ff0-e4d5-11e7-9492-98f5ec0bcbaa.png">

**Comment by german-e-mas** [comment]
Can you post the code? I can't tell how are you implementing it.

**Comment by pierre03** [comment]
Thank you, here is the code TS:

```
subscription: Subscription;
options: NgxGalleryOptions[];
images: NgxGalleryImage[];



constructor(private consultService:  ConsultService) {
this.options = [
{
image: false,
thumbnailsRemainingCount:  true,
height: '100px'
},

{
breakpoint: 500,
width: '50%',
thumbnailsColumns: 2
}

/* {
image: false,
width: '200px',
height: '100px',
imageArrowsAutoHide: true,
imageAutoPlay: true,
imageAutoPlayInterval: 1000,
thumbnailsRemainingCount: true
} */
];
```

**Comment by lukasz-galka** [comment]
default width is `400px` https://github.com/lukasz-galka/ngx-gallery#ngxgalleryoptions 
you can set any size or just `100%`

```
this.galleryOptions = [
            {
                width: '100%',
            }
]
```

**Comment by pierre03** [comment]
Hello,
Thank you for your response, but it changes nothing, in the code, i have tried to set the width to 50%, but it use always the default width.
I want to display juste 2 images, but with thumbnailsColumns: 2, it doesn't work.
Do you have any idea, please?

**Comment by TonganJedi** [comment]
Can we assume you are putting the code in the commented section up in the first option block?
