### ISSUE TITLE
Avoid cache picture

### ISSUE THREAD

**Issue by jlaverdure-talis** [lukasz-galka/ngx-gallery#86]
Hi,

First, thanks for this great module.

I just have one problem about it. 

Use of the module : 
I take profit of the NgxGalleryImage[] functions to add new images (via backend + push function) and delete them (via splice function).
The URL of the NgxGalleryImage contained in the array will **never change**, but the picture in the URL can change. (the backend server is doing all that stuff)
For example, it will ever be : 
- Picture A = "http://site/1.jpg"
- Picture B = "http://site/2.jpg"

Reproducing the problem :
- I push a FLOWER for picture A to the NgxGalleryImage[] : The FLOWER is showing
- I push a TRUCK for picture B to the NgxGalleryImage[] : The TRUCK is showing, perfect.
- I delete the picture A from the NgxGalleryImage[] via .splice() : OK
- I delete the picture B from the NgxGalleryImage[] via .splice() : OK, my array is empty.

Everything is OK until now.
- I try to push a CHOPPER for the picture A :  The FLOWER is showing. 
- I try to push a TREE for the picture B : The TRUCK is showing

Because it still considers the ancient pictures, even if these images no longer exist on the URL (replaced by CHOPPER and TREE. As if the picture was cached and not reloaded with the good value.

The cache cleaner solutions didn't solve my problem yet. I tried the lazy loading to false, but it didn't work too.

Did you encounter a similar problem? How can I avoid that? 
Thank you.

EDIT : Every cache cleaner done from the Angular project doesn't work. However, if I erase cache from the browser, the problem does not appear.

**Comment by lukasz-galka** [comment]
Hi @jlaverdure-talis this is not because of my gallery. Browser caches files and this is standard behaviour. You can avoid caching files by adding timestamp to url, for example:

```
 this.galleryImages = [
            {
                small: 'assets/1-small.jpg?t=' + Date.now(),
                medium: 'assets/1-medium.jpg?t=' + Date.now(),
                big: 'assets/1-big.jpg?t=' + Date.now()
            },
```

Alternatively you can set appropriate headers https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
more about caching here https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

**Comment by jlaverdure-talis** [comment]
Hi lukasz-galka, this is an awesome solution you got there, it worked perfectly.
Thank you for your answer.
