### ISSUE TITLE
the image shows very slow

### ISSUE THREAD

**Issue by laoniustudio** [lukasz-galka/ngx-gallery#88]
Hi, first thanks for your lib, very useful
I have 2 questions:
1, I do not know when i click to open preview of the image, it shows very slow, wait about 1-2 mins, i set the small,medium and big to be the same image. 
2, when i change the spiner icon to LineAwesome Icons: la la-spinner, it did not show, but it works for the arrowNextIcon
please help, thanks

**Comment by lukasz-galka** [comment]
Ji @laoniustudio 

1) I don't see this behaviour. here on plunker you can see that I also using the same image for small, medium and big https://plnkr.co/edit/nw2PHKNqtd3YPeqsMFAS?p=preview
Could you fork my plunker and try to reproduce your issue?

2) It depends which file you use. If you use file `line-awesome-font-awesome.css` you should use font awesome classes, so `fa fa-spinner`. If you use `line-awesome.css` then `la la-spinner`

**Comment by laoniustudio** [comment]
thanks, i will take a look at plunker. the la-spinner shows, but how to
make it spin?

**Comment by lukasz-galka** [comment]
font awesome has special classes for this, please take a lot on section `Animated Icons` here http://fontawesome.io/examples/

Default classes for gallery spinner looks like `fa fa-spinner fa-pulse fa-3x fa-fw`
https://github.com/lukasz-galka/ngx-gallery#ngxgalleryoptions
