### ISSUE TITLE
Not so much an issue but question...

### ISSUE THREAD

**Issue by SLK01** [lukasz-galka/ngx-gallery#89]
First off I really love what you'd done with this component. The best I saw todate.

I like to use this for my family website (personal), but I added some other features to my album as the users select individual thumbnails of a picture, I like to enable them with tagging the picture or show more details about the picture and so on. I am trying to learn how to latch on to a select event of this component. I am using Angular4. Could you please help?

Thanks in advance
Sam

**Comment by lukasz-galka** [comment]
hi @SLK01, please take a look on https://plnkr.co/edit/oVm8WjsfT9BnNa9mLjx6?p=preview
you can select images and watch `change` event

**Comment by SLK01** [comment]
Thank you so much ... again a great component and thanks for developing it.
