### ISSUE TITLE
Can't change default width and height

### ISSUE THREAD

**Issue by Ermenymw** [lukasz-galka/ngx-gallery#9]
Hi, Lukasz
    I can't find a way to change the default width and height. No matter what number I change the pixel for both parameters, they won't change anything in browser.
      this.galleryOptions = [
        {
          "previewFullscreen": true,
          "imageArrowsAutoHide": true,
         },
        {
          "breakpoint": 500,
          "width": "800px",     <---------I tried to change all these numbers
          "height": "600px",   <---------I tried to change all these numbers
          "thumbnailsColumns": 5
        },
        {
          "breakpoint": 300,
          "width": "100%",      <--------I tried to change all these numbers
          "height": "800px",    <--------I tried to change all these numbers
          "thumbnailsColumns": 4
         }
      ];

But nothing happened, the size stays as default.
Meanwhile, is it possible to make the whole gallery auto resizeable when the browser size changed? Otherwise if the browser is very small and the gallery will overflow since it is fixed size. Many thanks in advance.

**Comment by lukasz-galka** [comment]
Hi, breakpoints are working just like css media query 'max-width' 
https://www.w3schools.com/css/css_rwd_mediaqueries.asp

I have created simple demo with your configuration (I only changed width from 800px to 300px for breakpoint 500). You can resize browser or use chrome console to see this in action.
https://lukasz-galka.github.io/ngx-gallery-demo/custom#responsive-1

And in my opinion everything is working fine and with this configuration gallery has size:
width 500px and height 400px if browser width is bigger than 500px
width 100% and height 600px if browser is smaller than 500px and bigger than 300px
width 100% and height 800px if browser is smaller than 300px

If you still have some doubts please let me know.

**Comment by Ermenymw** [comment]
Got it, thankx for explanation. Now I realize what the three brace do. And one more question, what will "thumbnailsColumns": do it above two braces? I am assuming when browser is smaller than 500px and bigger than 300px, it will have 5 columns of thumbnails image and four when is smaller than 300px. While it never changes in my project.

**Comment by lukasz-galka** [comment]
Yes, you are right about 'thumbnailsCount'. Could you check on demo?
https://lukasz-galka.github.io/ngx-gallery-demo/custom#responsive-1

I have checked my demo and it works just as you described.
