### ISSUE TITLE
No instructions for Using Locally During Development

### ISSUE THREAD

**Issue by DMcNamara** [lukasz-galka/ngx-gallery#90]
Hi,

I'm starting to work on a few additions to this gallery (I'll make PRs when they're done), but I'm not able to figure out how to include my changed local copy into an existing Angular app for testing. I've done `npm run build` and gotten a `/dist` folder, which seems right. Then in package.json I added `"ngx-gallery": "file:../ngx-gallery/dist"` and installed. Doing an ng serve with this throws a `Critical dependency: the request of a dependency is an expression` warning, and loading the page throws an `Uncaught Error: Unexpected value 'NgxGalleryModule' imported by the module 'SharedModule'. Please add a @NgModule annotation.` error when loaded. 

I was hoping you had some guidance on how you test locally. I saw several references to playground, but that seems to be old.

Thanks!

**Comment by lukasz-galka** [comment]
Hi @DMcNamara you can use `npm link`, example usage here in `angular-cli` documentation https://github.com/angular/angular-cli#development-hints-for-working-on-angular-cli

**Comment by DMcNamara** [comment]
That worked perfectly, thanks!
