### ISSUE TITLE
Where to import hammerjs?

### ISSUE THREAD

**Issue by SouhaibBenFarhat** [lukasz-galka/ngx-gallery#91]
Hi guys, i'm trying to integrate ngx-gallery with my app and by reading the documentation they said that for swiping between images hummerjs is required, i can't find out where to import.

should i import hummerjs inside app.module or inside my component?

**Comment by lukasz-galka** [comment]
Hi @SouhaibBenFarhat, inside component

**Comment by SouhaibBenFarhat** [comment]
Thank you lukasz, your module is awesome, but is there any option that allow user to show directly the preview by clicking on the thumbnail?

**Comment by lukasz-galka** [comment]
Thumbnail will open preview if there is no image, you have to set `image` option to `false`

**Comment by SouhaibBenFarhat** [comment]
Done. Big thanks.
