### ISSUE TITLE
Dynamic images not showing...

### ISSUE THREAD

**Issue by sloke** [lukasz-galka/ngx-gallery#93]
Hi there:

I have a Photo Album with many directories and each directory contains many images, so I have a PhotoAlbum Component that recursively call an Express Route to get the image names from the directory. I used to have a Bootstrap Carousel component which was working but I replaced since then with ngx-gallery (cause I really like the presentation of this component). So each time a directory link is clicked, I reload the page with a new route - as a result I call the express route and fill the galleryImages with (small, medium, big) image links. I only see the very top directory working and subsequent directories with images are not loading but the area of ngx-gallery component on the page if I click I show the images in the preview. What am I missing?

Any pointers will be great.
Thanks
Srini

Here is the snippet of my HTML:
  <div class="col-sm-9 col-md-9 col-lg-9">
    <ngx-gallery (change)="catchChange($event);activeIndex=$event.index" 
      [options]="galleryOptions" [images]="galleryImages"></ngx-gallery>
  </div>

My Component code snippet:
  getAlbum(dir: string) {
    this.albumSvc.getAlbumData(dir).subscribe(success => {
      if (success) {
        console.log("retrieved album files successfully...");
        this.fillGalleryImages();
      }
    },
      error => console.log("error getting the album files...")
    );
  }

  fillGalleryImages() { 
    this.galleryImages = [];
    if (this.albumSvc.files != undefined) 
    {
      for (var i = 0; i < this.albumSvc.files.length; i++) {
        var imageData:NgxGalleryImage = {
            small: '/album/thumbs/' + this.albumSvc.files[i].name,
            medium: '/album/slides/' + this.albumSvc.files[i].name,
            big: '/album/' + this.albumSvc.files[i].name
        }
        this.galleryImages.push(imageData);
      }
    }
    console.log( "GalleryImages: %d", this.galleryImages.length );
    return this.galleryImages;
  }
Just to debug - I do see the console log, "retrieved album files successfully...", "Gallery Images: #of images" correctly printed but the ngx-gallery doesn't refresh. 

Please know that I am not an expert but with what I learned the images is bound to galleryImages of my component and whenever the array is changed the gallery should refresh.

**Comment by lukasz-galka** [comment]
Hi @sloke imo you code looks good. Do you use latest version? Could you paste output from `ng -v` and ` npm list view ngx-gallery`? Could you check html of gallery, are there new images?

In demo page there is example with dynamc images https://lukasz-galka.github.io/ngx-gallery-demo/#dynamic-images-change and this example works.

**Comment by sloke** [comment]
Can I see the code for your Dynamic Images Change page?

Here is the info you asked for:
	$ ng -v
	Angular CLI: 1.1.2
	Node: 6.11.4
	OS: Linux x64
	@angular/animations: 4.2.3
	@angular/common: 4.2.3
	@angular/compiler: 4.2.3
	@angular/compiler-cli: 4.2.3
	@angular/core: 4.2.3
	@angular/forms: 4.2.3
	@angular/http: 4.2.3
	@angular/platform-browser: 4.2.3
	@angular/platform-browser-dynamic: 4.2.3
	@angular/platform-server: 4.2.3
	@angular/router: 4.2.3
	@angular/cli: 1.1.2
	
	$npm list view ngx-gallery
	ngx-gallery@4.1.2

Thanks Again
Srini

**Comment by sloke** [comment]
Also ... if a directory has 250 images ... is there a way to only load images that are currently being displayed (Lazy Loading..) ? 

Thanks for your support.

**Comment by lukasz-galka** [comment]
@sloke, lazy loading is enabled by default, you can disable it using option `lazyLoading`, more here https://github.com/lukasz-galka/ngx-gallery#ngxgalleryoptions

my code is available on github, please take a look at https://github.com/lukasz-galka/ngx-gallery-demo/blob/master/src/app/app.component.ts#L218

in this example I am using methods `changeImages`, `addImage` and `removeImage`

**Comment by SLK01** [comment]
Ah... I found the issue. It is not the component issue, it was the URLs I was creating dynamically when each of the sub-directories were selected. I got that corrected and it is working. 

One other thing you can help me. I'd broken the screen to two parts, col-9 for ngx-gallery and col-3 for image info and rating/tagging etc. but the component doesn't show images. For that I have to give Width/Height, is there a way to show thumbnails and gallery to show vertical & horizontal oriented images? (I have used imageSize: contain but thumbnails still look chopped - and the left/right arrows feel disappeared because they are camouflaged within white background)

Thanks

**Comment by lukasz-galka** [comment]
@SLK01 you can also set contain to thumbnails, using option `thumbnailSize`. You can also change style of arrows uysing css, you can find examples in closed issues. 

If there still is a problem please add some image with example.

**Comment by SLK01** [comment]
Actually by turning the background of the div tag that contains the ngx-gallery to some darker color helps with the arrows to pop up. thumbnailSize contain helped, thank you. Now I have to play with turning the slideshow on dynamically as well as removing the thumbnails when there is only one picture in the directory. All set, thank you so much.
