### ISSUE TITLE
how to implement a button to close image preview 

### ISSUE THREAD

**Issue by faribajpr** [lukasz-galka/ngx-gallery#94]
hi, i'm new in angular  and i'm using ngx-gallery!in my gallery i can preview images in fullscreen mode by default but there is no close button! i don't know how to implement this button! how can i do in only in one component.ts file?
 this is part of html:

`<div fxLayout="row" fxLayoutAlign="center center" class="mt-1">

              <a class="chevron" (click)="gallery.showPrev()" disabled="!gallery.canShowPrev()"><md-icon>chevron_left</md-icon></a>
              <ngx-gallery #gallery [options]="galleryOptions" [images]="galleryImages">
              </ngx-gallery>
              <a (click)="gallery.showNext()" disabled="!gallery.canShowNext()"><md-icon>chevron_right</md-icon></a>
            </div>`

and this is my component.ts:

` this.galleryImages =[
      {
        small: '/assets/images/face1.jpg',
        medium: '/assets/images/face1.jpg',
        big: '/assets/images/face1.jpg'
      },
      {
        small: '/assets/images/face2.jpg',
        medium: '/assets/images/face2.jpg',
        big: '/assets/images/face2.jpg'
      },
      {
        small: '/assets/images/face3.jpg',
        medium: '/assets/images/face3.jpg',
        big: '/assets/images/face3.jpg'
      }
    ]
    this.galleryOptions = [
      {
        width: '600px',
        height: '1100px',
        thumbnailsColumns: 4,
        imageAnimation: NgxGalleryAnimation.Slide
      },
      // max-width 800
      {
        breakpoint: 400,
        // width: '2%',
        // height: '2px',
        imagePercent: 99,
        thumbnailsPercent: 1,
        thumbnailsMargin: 20,
        thumbnailMargin: 20,
        thumbnailsArrows: true,
        thumbnailsSwipe:true
      },
      // max-width 400
      {
        breakpoint: 400,
        preview: false
      }
    ];`

**Comment by lukasz-galka** [comment]
Hi @faribajpr this components uses font awesome for icons, more here https://github.com/lukasz-galka/ngx-gallery#prerequisites 

if you dont't use font awesome, you can use your own icons and pass class for close button to component using option `closeIcon `, more here https://github.com/lukasz-galka/ngx-gallery#ngxgalleryoptions

**Comment by faribajpr** [comment]
oh thanks a lot @lukasz-galka!! its's ok now!!
and how can i change the icon's color?
