### ISSUE TITLE
what can we do if we have multiple images that will load dynamically 

### ISSUE THREAD

**Issue by santhoshrajuvysyaraju** [lukasz-galka/ngx-gallery#96]
hi i want to add images dynamically to the slider. how can i create gallery images dynamically

**Comment by lukasz-galka** [comment]
@santhoshrajuvysyaraju check closed issue, this was fixed many times. If there still is a problem please show your current code.

**Comment by santhoshrajuvysyaraju** [comment]
my images are contained in json data that retrived from api url . those data displayig only in browser and i dont know to use those data inside the my typesript. i have coded some how . please check the link  contains my code.

https://stackoverflow.com/questions/48151133/how-to-assign-part-of-string-data-to-an-array-in-angular5
