### ISSUE TITLE
what does braces mean in ngx-gallery?

### ISSUE THREAD

**Issue by faribajpr** [lukasz-galka/ngx-gallery#97]
this is the code in example of ngx-gallery :
`this.galleryOptions = [
            {
                width: '600px',
                height: '400px',
                thumbnailsColumns: 4,
                imageAnimation: NgxGalleryAnimation.Slide
            },
            // max-width 800
            {
                breakpoint: 800,
                width: '100%',
                height: '600px',
                imagePercent: 80,
                thumbnailsPercent: 20,
                thumbnailsMargin: 20,
                thumbnailMargin: 20
            },
            // max-width 400
            {
                breakpoint: 400,
                preview: false
            }
        ];`  
but i don't understand it!
and i have another question, how can i print images that i'm showing in ngx-gallery? and can i resize them before printing? for example in A4 or sometimes B2?
i'll be really thankful if you help me!

**Comment by lukasz-galka** [comment]
@faribajpr with `breakpoint` option  you can define different behaviour for responsive. So in your example gallery will have width 100% if screen is smaller than 800px and will have width 600px if screen is bigger than 800px

**Comment by faribajpr** [comment]
i understand now!tnx a lot!

**Comment by cdr72ex** [comment]
I know that you closed the issue, but I hope that you see this again. I had the same question about the different braces. Would you please add some information to your README to clarify what the different braces do?
