### ISSUE TITLE
Styling Icons (Medium Image v. Large Image Icons)

### ISSUE THREAD

**Issue by TonganJedi** [lukasz-galka/ngx-gallery#98]
I was adjusting the CSS on the arrows to play with shape and color when I noticed an irregularity between the icons used on the medium and large images.

`ngx-gallery /deep/ .ngx-gallery-arrow {
    color: black;
    background-color: goldenrod;
    border-radius: 50%;
    font-size: 50px;
    width: 50px;
    height: 50px;
    line-height: 50px;
    text-align: center;
    vertical-align: middle;
}`

I increased the medium image icon size for comparison. Notice the fatter right side.
![image](https://user-images.githubusercontent.com/30245030/34690211-7da7870a-f475-11e7-896f-5df71ab67826.png)

The large image icon is centered:
![image](https://user-images.githubusercontent.com/30245030/34690389-329c026c-f476-11e7-8d0f-741307b63bb5.png)

Is there a way to target them separately?

**Comment by TonganJedi** [comment]
Something else I noticed--I can change the font-size attribute (as you can see from the previous post), but it only affects the medium image icons. The large image icons stay the same. Yet other css attributes DO affect the large icons. It's annoyingly inconsistent.

Appreciate any guidance you might have.

**Comment by TonganJedi** [comment]
Here's what the large icons look like if I set a hard 25px height/width on the icons (required to center and round their backgrounds):

![image](https://user-images.githubusercontent.com/30245030/34691229-33f0b16e-f479-11e7-9d79-f9263b289ef0.png)

Unsure why the arrow is shoved into the side of the browser window.

**Comment by TonganJedi** [comment]
We could use a way to manipulate the small image icons separately from the other icons as well.

**Comment by TonganJedi** [comment]
Turns out that odd 1 px offset only appears in Chrome. IE11 and Firefox don't display it.

**Comment by lukasz-galka** [comment]
@TonganJedi, yes you can specify inner component in selector

```
ngx-gallery /deep/ ngx-gallery-image .ngx-gallery-arrow {
}
ngx-gallery /deep/ ngx-gallery-thumbnails .ngx-gallery-arrow {
}
ngx-gallery /deep/ ngx-gallery-preview .ngx-gallery-arrow {
}
```

In version `4.2.1` I have fixed issue with font size

**Comment by TonganJedi** [comment]
Thank you! I'll do some testing on it (assuming I have a job on Monday, which is in doubt).
